fylein/fyle-mobile-app

src/app/fyle/my-create-report/my-create-report.page.html
src/app/fyle/my-expenses/my-expenses.page.ts

- update count on delete expense
- showing trip id in 0 states of creating a report

final fixes 59

---

src/app/core/interceptors/httpInterceptor.ts

reference: https://stackoverflow.com/questions/45428842/angular-url-plus-sign-converting-to-space/52458069#52458069

interceptor changes to encode URL

---

src/app/fyle/my-expenses/my-expenses-card/my-expenses-card.component.html

old app
new app without changes
new app with changes
check 660 rs expense, taxi category

fix in my-expense category icon

---

src/app/fyle/my-view-report/share-report/share-report.component.html
src/app/fyle/my-view-report/share-report/share-report.component.ts

- On validating the entered email with pattern, if the input email is invalid; an error message will be shown
- Loom Video - https://www.loom.com/share/a3ff02113da8472897c5dbcab4c6cf2e

Changes for adding Invalid email check in share report on View report page

---

src/app/auth/sign-in/error/error.component.html
src/app/auth/sign-in/sign-in.page.ts

< ------  new  ------  >
< ------  old  ------  >

Updated Message, when some internal server error comes

---

src/app/fyle/view-team-report/view-team-report.page.html

<------ new ------>
<----- old ------->

resolved template ref err

---

src/app/fyle/split-expense/split-expense.page.html
src/app/fyle/split-expense/split-expense.page.ts

When only 2 split expenses, the remaining amount/percentage will be filled onto other split expense.

Split Expense Behaviour Changes

---

src/app/fyle/split-expense/split-expense.page.ts

Floating Point Bug in Amount

---

src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.html
src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.scss
src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.ts

Unmatch CTA border color needs to be fixed in new mobile app

---

src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.html
src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.scss
src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts

removed validation changes for custom values in userlist

---

src/app/fyle/corporate-card-expenses/corporate-card-expenses.page.html
src/app/fyle/dashboard/dashboard.page.html
src/app/fyle/help/help.page.html
src/app/fyle/my-advances/my-advances.page.html
src/app/fyle/my-expenses/my-expenses.page.html
src/app/fyle/my-profile/my-profile.page.html
src/app/fyle/my-reports/my-reports.page.html
src/app/fyle/my-trips/my-trips.page.html
src/app/fyle/team-advance/team-advance.page.html
src/app/fyle/team-reports/team-reports.page.html
src/app/fyle/team-trips/team-trips.page.html
src/app/shared/components/fy-menu-icon/fy-menu-icon.component.html
src/app/shared/components/fy-menu-icon/fy-menu-icon.component.scss
src/app/shared/components/fy-menu-icon/fy-menu-icon.component.spec.ts
src/app/shared/components/fy-menu-icon/fy-menu-icon.component.ts
src/app/shared/shared.module.ts
src/assets/svg/fy-menu.svg

FYLE-39acgn: Menu icon component

---

src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.html
src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.scss
src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts

https://user-images.githubusercontent.com/31820553/119609155-bc238580-be14-11eb-9af8-ac629de9d5fc.mov

Fix for input not getting focused after filtered list is loaded

---

src/app/fyle/my-profile/my-profile.page.html

FYLE-3vfnz6 Fix Default currency settings option

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.scss
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/shared/icon/icon.module.ts

FYLE-3xeygj: Split expense in expense form

---

src/app/fyle/add-edit-expense/fy-currency/fy-currency-exchange-rate/fy-currency-exchange-rate.component.html
src/app/fyle/add-edit-expense/fy-currency/fy-currency-exchange-rate/fy-currency-exchange-rate.component.scss
src/app/fyle/add-edit-expense/fy-currency/fy-currency.component.ts
src/app/fyle/split-expense/split-expense.page.html
src/app/fyle/split-expense/split-expense.page.scss
src/app/shared/components/fy-alert-info.component.html/fy-alert-info.component.scss
src/global.scss

FYLE-43jj1y: Currency converter changes

---

src/app/app.component.ts
src/app/fyle/camera-overlay/camera-overlay.page.ts
src/app/fyle/corporate-card-expenses/corporate-card-expenses.page.ts
src/app/fyle/my-expenses/my-expenses.page.ts
src/app/fyle/my-reports/my-reports.page.ts
src/app/fyle/team-reports/team-reports.page.ts

Fixed Hardware back Button on all pages. Also triggered exit popup on the Login page.

Fyle-3xhba9 Fixed: Hardware Back Button

---

src/app/fyle/add-edit-expense/add-edit-expense.page.scss

FYLE-49aymu: Fixed amount error alignment

---

src/app/fyle/my-expenses/my-expenses.page.html
src/app/fyle/my-expenses/my-expenses.page.scss

FYLE-49fazr: Zero state alignment fixed in expenses page

---

src/app/shared/components/fy-multiselect/fy-multiselect-modal/fy-multiselect-modal.component.html
src/app/shared/components/fy-multiselect/fy-multiselect-modal/fy-multiselect-modal.component.scss
src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.html
src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.scss
src/assets/styles/_fy_select.scss

FYLE-49b1rh: Replacing multi/user select cta buttons with header action buttons

---

src/app/shared/components/fy-multiselect/fy-multiselect-modal/fy-multiselect-modal.component.html
src/app/shared/components/fy-multiselect/fy-multiselect-modal/fy-multiselect-modal.component.scss
src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.html
src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.scss
src/app/shared/components/fy-select-vendor/fy-select-modal/fy-select-vendor-modal.component.html
src/app/shared/components/fy-select-vendor/fy-select-modal/fy-select-vendor-modal.component.scss
src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.html
src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.scss
src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.html
src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.scss
src/assets/styles/_fy_select.scss

Note: User select and multi-select pop-up changes taken care of in a different pr.

FYLE-4bhwtv: Added search icons to search bar wherever missing

---

.eslintrc.json
package-lock.json
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/shared/components/fy-alert-info.component.html/fy-alert-info.component.ts
src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
src/app/shared/components/fy-select/fy-select.component.ts
src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.ts
src/app/shared/components/route-selector/route-selector.component.ts

Fixed linting error after merged to master.

Fixed Linting

---

src/app/fyle/my-view-report/my-view-report-etxn-card/my-view-report-etxn-card.component.html
src/app/fyle/my-view-report/my-view-report-etxn-card/my-view-report-etxn-card.component.scss
src/app/shared/components/expenses-card/expenses-card.component.html
src/app/shared/components/expenses-card/expenses-card.component.scss

fix-unit-case: Fixing distance unit to lower case wherever used

---

src/app/fyle/add-edit-expense/add-edit-expense.page.scss

checked all resolutions, working fine

exchange-rate-fix: Fixing alignment of amount error when exchange rate is present and amount is 0

---

src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
src/global.scss

payment mode bug fix

---

src/app/fyle/dashboard/stats/stats.component.scss
src/app/shared/components/fy-header/fy-header.component.scss
src/global.scss

Changes [here](https://www.notion.so/fyleuniverse/Header-bar-bb3cea121b004db2b690523757eb6fb9)

Make header bar height same as figma design

---

src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.scss
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.scss

Updated mileage page
Updated per diem page
Old per diem page
Old mileage page

Move amount in mileage, per-diem page and add secondary cta in mileage

---

src/app/shared/components/comments-history/audit-history/audit-history.component.html
src/app/shared/components/comments-history/audit-history/audit-history.component.scss
src/app/shared/components/comments-history/audit-history/statuses-diff/statuses-diff.component.html
src/app/shared/components/comments-history/audit-history/statuses-diff/statuses-diff.component.scss

Align violating transactions in history section

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.scss
src/app/shared/components/comments-history/view-comment/view-comment.component.html
src/app/shared/components/comments-history/view-comment/view-comment.component.scss
src/app/shared/components/comments-history/view-comment/view-comment.component.ts

- Hide drag bar in android
Before
After
- Add right margin to delete icon
Before:
After:
- Add padding in history section
Before:
After:

Some minor fixes

---

src/app/fyle/add-edit-expense/add-edit-expense.page.ts

https://app.clickup.com/t/7q87cy

Fix for amount error issue when extracted data has foreign amount

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.scss
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.scss
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.scss
src/app/shared/components/comments-history/view-comment/view-comment.component.ts

Discard comments popup:
https://user-images.githubusercontent.com/39493102/131531709-5be2f253-5b04-4c9b-9f04-24005216ea83.mp4
Cancel cta in edit expenses:
https://user-images.githubusercontent.com/39493102/131531808-b581955e-68ea-464a-b91e-9a9e1daff912.mp4

Add discard comments popup and cancel cta in edit expenses

---

src/app/fyle/add-edit-expense/fy-currency/fy-currency.component.scss

Fix for amount error with foreign currency and receipt preview

---

src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/shared/components/fy-view-attachment/fy-view-attachment.component.html
src/app/shared/components/fy-view-attachment/fy-view-attachment.component.scss
src/app/shared/components/fy-view-attachment/fy-view-attachment.component.ts

Before:
After:
https://user-images.githubusercontent.com/39493102/132251624-a1570df1-c0fb-42f8-86f3-4ba8a321dc8e.mp4

Make receipt preview fullscreen and update delete popover

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.scss
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.scss
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.scss
src/app/fyle/dashboard/stat-badge/stat-badge.component.ts
src/app/fyle/my-expenses/my-expenses.page.ts

Cannot read property 'ou' of null - sentry:
Before:
https://user-images.githubusercontent.com/39493102/131646712-bfb64e3d-974f-4fc3-ad70-98320cf0ee45.mp4
After:
https://user-images.githubusercontent.com/39493102/131646703-8b2b3db5-a925-4035-a2d6-6e24cb9eef13.mp4
Align headers in my  expenses page
Before:
After

Resolve eou not defined, align my expenses headers and disable backdrop clicks in delete popover 

---

src/app/fyle/team-reports/team-report-card/team-report-card.component.html
src/app/fyle/team-reports/team-report-card/team-report-card.component.scss
src/app/fyle/team-reports/team-report-card/team-report-card.component.ts

FYLE-b9ng77: Team reports page revamp - 1

---

src/global.scss

Fix view-comment headers in ios

---

src/app/fyle/add-edit-advance-request/policy-violation-dialog/policy-violation-dialog.component.html
src/app/fyle/add-edit-advance-request/policy-violation-dialog/policy-violation-dialog.component.scss
src/app/fyle/add-edit-expense/policy-violation/policy-violation.component.html
src/app/fyle/add-edit-expense/policy-violation/policy-violation.component.scss
src/app/fyle/add-edit-mileage/policy-violation/policy-violation.component.html
src/app/fyle/add-edit-mileage/policy-violation/policy-violation.component.scss
src/app/fyle/add-edit-per-diem/policy-violation/policy-violation.component.html
src/app/fyle/add-edit-per-diem/policy-violation/policy-violation.component.scss

Change policy violation cta design

---

.github/workflows/manual-appflow-1.yml

Reverts fylein/fyle-mobile-app2#653

Revert "slack message fix"

---

src/app/fyle/my-view-expense/my-view-expense.page.html

https://sentry.io/organizations/fyle-technologies-private-limi/issues/2660608726/?project=5622998&referrer=slack

Fix for provider not found sentry error

---

src/global.scss

FYLE-cqkder: Fixed the spacing of loader and text in delete pop up

---

src/app/fyle/view-team-report/send-back/send-back.component.html
src/app/fyle/view-team-report/send-back/send-back.component.scss
src/app/fyle/view-team-report/send-back/send-back.component.ts
src/app/fyle/view-team-report/view-team-report.module.ts
src/app/fyle/view-team-report/view-team-report.page.html
src/app/fyle/view-team-report/view-team-report.page.scss
src/app/fyle/view-team-report/view-team-report.page.ts
src/global.scss

https://user-images.githubusercontent.com/39493102/134042621-559b2113-b118-4764-be07-24b618813181.mp4

Update sent back report flow

---

src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html

FYLE-cqkpqz: changed 1 expenses to 1 expense in add to report popup

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/fy-currency/fy-currency.component.ts

Reverts fylein/fyle-mobile-app2#657

Revert "FYLE-bfm4jd: Update exchange rate and amount on changing date of spend"

---

src/app/fyle/my-advances/my-advances.page.html
src/app/fyle/my-advances/my-advances.page.ts

FYLE-cx4y9d: updated advances page to new design

---

src/app/app.module.ts
src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
src/app/fyle/my-view-advance-request/my-view-advance-request.page.scss
src/app/fyle/my-view-advance-request/my-view-advance-request.page.ts
src/app/fyle/view-team-advance/view-team-advance.page.html
src/app/fyle/view-team-advance/view-team-advance.page.scss
src/app/fyle/view-team-advance/view-team-advance.page.ts

Fyle-cx5b5g: moved the comment option to header in team advance

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html

pre commits related to updating exchange rate when the date of spend changes:
- https://github.com/fylein/fyle-mobile-app2/pull/657/files
- https://github.com/fylein/fyle-mobile-app2/pull/680/files
Note: This HTML code was missing master due to a conflict resolved (No impact - once this pr is merged, the exchange rate will update based on change of date of spend)

FYLE-bfm4jd-1: Updated input of txn date for currency component 

---

src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.html
src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.scss

FYLE-cx8w25: Change policy violation content

---

src/app/core/services/tracking.service.ts
src/app/fyle/my-reports/my-reports.page.html
src/app/fyle/my-reports/my-reports.page.scss
src/app/fyle/my-reports/my-reports.page.ts

FYLE-cqf2uk-1: Search, Sort and Filter in Reports page

---

src/app/fyle/my-view-advance-request/my-view-advance-request.page.ts
src/app/fyle/my-view-advance-request/pull-back-advance-request/pull-back-advance-request.component.html
src/app/fyle/my-view-advance-request/pull-back-advance-request/pull-back-advance-request.component.scss

FYLE-cx5ayw: updated the pull back advance popup to new design

---

src/app/fyle/my-advances/my-advances.page.html

FYLE-1rwvhr0: changed `+` in advances zero state

---

src/app/fyle/team-reports/team-reports.page.ts

FYLE-1tkvq75: Added default filter in team reports page for approvers to view the approver pending reports by default

---

src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts

fix - 1rwz31w : Fixed Change the receipt preview component to be full screen in add edit advance page

---

src/app/shared/components/expenses-card/expenses-card.component.scss

Fyle 1u522kk : Fixed Incomplete Status Pill in Expenses

---

src/app/fyle/add-edit-advance-request/fy-currency/fy-currency-choose-currency/fy-currency-choose-currency.component.html
src/app/fyle/add-edit-advance-request/fy-currency/fy-currency-choose-currency/fy-currency-choose-currency.component.scss
src/app/fyle/add-edit-expense/fy-currency/fy-currency-choose-currency/fy-currency-choose-currency.component.html

1tz8pjr : Fixed The selected item check mark colour should be brand primary in list pop ups

---

src/app/fyle/notifications/notifications.page.html

Fix : 1ugb2y0 Fixed Can't find the Save cta until page is scrolled to the end in Notification

---

src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts

Changing "Claim number " to "Report Number" in ( Report View Page --> View Info --> "Report Number" ) in fyle-mobile-app.

Changing Claim number  to Report Number in Mobile app

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html

Fix 1ug8brx : Fixed Hide `Please select a project` when project is not assigned to user but it is mandatory 

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.scss
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.scss
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.scss
src/global.scss

Fyle 1uvx789 : Fixed change top Information Box to Alert Box in expense/mileage/per diem pages

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html

Fyle 1v1hkjc : Fixed 'Please add a project ' alignment in Expenses

---

src/app/app.component.ts
src/app/auth/switch-org/active-org-card/active-org-card.component.html
src/app/auth/switch-org/active-org-card/active-org-card.component.scss
src/app/auth/switch-org/org-card/org-card.component.html
src/app/auth/switch-org/org-card/org-card.component.scss
src/app/auth/switch-org/switch-org.page.html
src/app/auth/switch-org/switch-org.page.scss
src/app/auth/switch-org/switch-org.page.ts

https://www.loom.com/share/6e60e746a76c444e8551992cb362ccd7

Switch-org page: Add back btn, search animation, make search sticky, fix shimmers and other minor fixes 

---

src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/my-view-report/my-view-report.page.ts

fixed : Send Report Id From View Report on click of add expense

---

src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
src/app/fyle/view-expense/view-expense.page.scss
src/app/fyle/view-team-report/view-team-report.page.scss

Add 'Add more' cta in add/edit advances page and view-expense flag

---

src/app/fyle/my-advances/my-advances.page.html
src/app/fyle/my-advances/my-advances.page.ts
src/app/fyle/team-advance/team-advance.page.html
src/app/fyle/team-advance/team-advance.page.ts

Reverts fylein/fyle-mobile-app#803

Revert "Fyle 1x64m5r : Adding shimmers to my-advances page"

---

src/app/auth/switch-org/active-org-card/active-org-card.component.html
src/app/auth/switch-org/active-org-card/active-org-card.component.ts
src/app/auth/switch-org/switch-org.page.html
src/app/auth/switch-org/switch-org.page.scss
src/app/auth/switch-org/switch-org.page.ts

Changes:
- Hide active org card when user logs in
- Make searchbar sticky only in android
- Show default org at top of list
- Make active org card clickable
https://www.loom.com/share/62c3d86196ac40829427d42272c48d8a

Switch org revamp fix

---

src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.html
src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.scss
src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.ts
src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.html
src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.scss
src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.ts
src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.scss
src/app/shared/components/sidemenu/sidemenu.component.html
src/app/shared/components/sidemenu/sidemenu.component.ts

Fixes:
- Show option directly if only one option inside dropdown (Cards / Teams)
- Add divider between primary and secondary options
- Fix padding and alignment issues

Resolve sidemenu comments

---

src/app/fyle/my-profile/employee-details-card/employee-details-card.component.ts
src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
src/app/shared/components/fy-input-popover/fy-input-popover.component.html
src/app/shared/components/fy-input-popover/fy-input-popover.component.ts

In this fix I've made mobile number not mandatory to get it updated

Changes for FYLE-1zaxwrz

---

src/app/core/models/org_user_settings.model.ts
src/app/fyle/notifications/notifications.page.html
src/app/fyle/notifications/notifications.page.ts

Added 'Notify only me' option to notification settings
Also fixed an existing issue for which sharing the corresponding loom video below
https://www.loom.com/share/d6639d458d6f408da074cfe9698ddd83

Changes for FYLE-1zaxqgx

---

src/app/fyle/my-profile/employee-details-card/employee-details-card.component.html
src/app/fyle/my-profile/employee-details-card/employee-details-card.component.ts

Changes for FYLE-1zaxwp4
Change: 
https://www.loom.com/share/7a74cbb08f2b46acbaed32b737b2741b
The suggestion in the video has been accepted and pushed here

FYLE-1zaxwp4

---

src/app/fyle/capture-receipt/receipt-preview/receipt-preview.component.ts

Fixed typo: `base64ImagesWithSource` -> `base64ImageWithSource` and update image base64

Fix crop receipt

---

src/app/core/models/org_user_settings.model.ts
src/app/fyle/notifications/notifications.page.html
src/app/fyle/notifications/notifications.page.ts

Reverts fylein/fyle-mobile-app#839

Revert "Changes for FYLE-1zaxqgx"

---

src/app/shared/components/fy-input-popover/fy-input-popover.component.html

Asterix will be displayed in pop over component only if the value is mandatory

Popover component - Asterix will be displayed only if the value is mandatory

---

src/app/core/services/trip-requests.service.ts
src/app/fyle/my-add-edit-trip/my-add-edit-trip.page.html
src/app/fyle/my-add-edit-trip/my-add-edit-trip.page.ts
src/app/fyle/my-trips/my-trips.page.html
src/app/fyle/my-trips/my-trips.page.ts
src/app/fyle/my-view-trips/my-view-trips.page.html
src/app/fyle/my-view-trips/my-view-trips.page.ts
src/app/fyle/team-trips/team-trips.page.html
src/app/fyle/team-trips/team-trips.page.ts
src/app/fyle/view-team-trip/view-team-trip.page.html
src/app/fyle/view-team-trip/view-team-trip.page.ts
src/global.scss

Dates for deprecation - 7th Feb for spenders and 28th Feb for approvers
For 15 orgs under SIS and 2 orgs under KARAM - 31st March for spenders and 30th April for approvers
Spender-
Approvers-

Add trips deprecation message

---

src/app/auth/switch-org/active-org-card/active-org-card.component.scss
src/app/auth/switch-org/org-card/org-card.component.scss

Fix pill text overflow

---

src/app/core/services/transactions-outbox.service.ts

This reverts commit 27b3e58fc042910c3e7e9df57a45de7bbb52cbfa.

Revert "deprecated old DE endpoint"

---

src/app/core/services/location.service.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
src/app/shared/components/route-visualizer/route-visualizer.component.ts

For devices in which gps does not turn on even after giving permission:
https://user-images.githubusercontent.com/39493102/151952466-846ff0be-0efe-47e3-afbd-f76314b9dcec.mp4
After manually turning on gps (after 10 mins) or switching to another org:
https://user-images.githubusercontent.com/39493102/151952471-bd159292-a191-4a17-afa7-5d1bc07079de.mp4

Fix mileage page not loading in some devices

---

src/app/core/services/transactions-outbox.service.ts

This reverts commit 42fe28524715457007b181b60338b77dc6cd7e08.

reverted revert of depreciating old DE endpoint 

---

src/app/core/services/trip-requests.service.ts
src/app/fyle/my-trips/my-trips.page.html
src/app/fyle/my-trips/my-trips.page.ts

For orgs without extension:
For orgs with extension:

Disable New trip request cta and update deprecation msg

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.scss
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/theme/colors.scss

Reverts fylein/fyle-mobile-app#829

Revert "FYLE-1z55me7: Prompt report submission mobile app changes"

---

src/app/core/models/org_user_settings.model.ts
src/app/core/services/offline.service.ts
src/app/fyle/notifications/notifications.page.html
src/app/fyle/notifications/notifications.page.ts

Reverts fylein/fyle-mobile-app#860

Revert "Implemented notify me only under delegatee notification settings"

---

package-lock.json

https://www.notion.so/fyleuniverse/Audit-fix-for-soc2-68a2192b02eb40c49678afb44d501eab

Audit fix for #soc2

---

src/app/shared/components/fy-zero-state/fy-zero-state.component.ts

Click up link: https://app.clickup.com/t/21ffmem

Undefined error in zero state component has been resolved using optional chaining

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.scss
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/theme/colors.scss

These changes are already reviewed

FYLE-1z55me7-2: Prompt report submission changes in expense form

---

src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.scss
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.scss
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts

Reverts fylein/fyle-mobile-app#881

Revert "FYLE-1z55me7-1: Prompt report submission  changes in mileage and per diem page"

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.scss
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/theme/colors.scss

Reverts fylein/fyle-mobile-app#888

Revert "FYLE-1z55me7-2: Prompt report submission changes in expense form"

---

src/app/shared/components/capture-receipt/crop-receipt/crop-receipt.component.ts
src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.ts

Before:
https://user-images.githubusercontent.com/39493102/153432261-050f21e1-417d-41e0-aab4-9efc907056bc.mp4
After:
https://user-images.githubusercontent.com/39493102/153431731-c8a5d572-12e5-4f31-91d2-c6d353564f9e.mp4

Fix: Android hardware back button issue in crop receipt

---

src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.scss
src/app/fyle/add-edit-expense/add-edit-expense.page.scss
src/app/shared/components/fy-number/fy-number.component.scss

Fix alignment of Please enter amount text

---

src/app/fyle/view-team-advance/view-team-advance.page.ts

Advance actions header fix

---

.gitignore
package-lock.json
src/app/core/services/trip-requests.service.ts
src/app/fyle/my-trips/my-trips.page.html
src/app/fyle/my-trips/my-trips.page.ts
src/app/fyle/my-view-trips/my-view-trips.page.html
src/app/fyle/my-view-trips/my-view-trips.page.ts
src/app/fyle/view-team-trip/view-team-trip.page.html
src/app/fyle/view-team-trip/view-team-trip.page.ts

https://www.loom.com/share/be20c61a0daa4faf8ad9fb5650deaeeb

Hide trip cta for orgs without extension

---

.gitignore
src/app/fyle/add-edit-advance-request/camera-options-popup/camera-options-popup.component.html
src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.html
src/app/fyle/my-expenses/my-expenses.page.html
src/app/fyle/my-expenses/my-expenses.page.ts
src/app/shared/components/expenses-card/expenses-card.component.html
src/app/shared/components/expenses-card/expenses-card.component.ts

https://user-images.githubusercontent.com/39493102/154623706-a1af563c-11f0-4c86-9be1-572bd52d7901.mp4

Add fyle camera in my-expenses page

---

src/app/fyle/split-expense/split-expense.page.html
src/app/fyle/split-expense/split-expense.page.scss
src/app/fyle/split-expense/split-expense.page.ts
src/app/shared/components/fy-number/fy-number.component.html
src/app/shared/components/fy-number/fy-number.component.ts

Reverts fylein/fyle-mobile-app#922

Revert "Split Expense Decimal"

---

src/app/shared/components/comments-history/view-comment/view-comment.component.scss
src/app/shared/components/summary-tile/summary-tile.component.scss
src/theme/colors.scss

Sharing the screenshots of the fixes
-images.githubusercontent.com/97864484/158582555-8a1a6098-9c4f-48ad-9afc-b263e4f1ebb5.

Issues on view advance/advance request pages fixed

---

android/app/build.gradle
android/app/src/main/assets/capacitor.config.json
hooks/prebuild.js
src/app/core/services/transactions-outbox.service.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.ts
src/app/fyle/my-expenses/my-expenses.page.ts
src/main.ts

https://www.notion.so/fyleuniverse/Vapt-q1-2022-fa65f76bc48f48f68e2974c07f7738da#e3aaa672a630475a86d0e3ecaf501682

Remove console logs from application

---

src/app/fyle/view-expense/view-expense.page.html
src/app/fyle/view-expense/view-expense.page.scss
src/app/fyle/view-expense/view-expense.page.ts

FYLE-2459yz4: Unify ccce expenses flow - View expense changes

---

src/app/shared/components/sidemenu/sidemenu.component.ts

FYLE-2459z0j: Unify ccce expenses flow - Sidebar changes

---

src/app/shared/components/fy-connection/fy-connection.component.scss

when the app is offline the colour will back but when it is online the colour I set to white

changed colour to white when connection is online

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.scss
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/view-expense/view-expense.page.html
src/app/fyle/view-expense/view-expense.page.scss

Unify ccce expenses flow - Fixes-1

---

hooks/secrets.js

Fix for issue - https://www.notion.so/fyleuniverse/Vapt-q1-2022-fa65f76bc48f48f68e2974c07f7738da#716c6413682b4ce58a4ffdd5222e1ae9
🍏 Tested on device

Disable Insecure HTTP loads on localhost

---

src/app/shared/components/expenses-card/expenses-card.component.scss

Reverts fylein/fyle-mobile-app#968

Revert "2px Spacing between currency and amount"

---

src/app/shared/components/fy-connection/fy-connection.component.scss

Reverts fylein/fyle-mobile-app#973

Revert "changed colour to white when connection is online"

---

android/app/build.gradle
android/app/proguard-rules.pro
android/app/src/main/AndroidManifest.xml

Reverts fylein/fyle-mobile-app#963

Revert "Disable backup and obfuscate bytecode"

---

hooks/secrets.js

Reverts fylein/fyle-mobile-app#977

Revert "Disable Insecure HTTP loads on localhost"

---

src/app/shared/components/expenses-card/expenses-card.component.scss
src/app/shared/components/fy-connection/fy-connection.component.scss

1px space between amount and currency
colour changed to white when online

Committing the changes again after hot fix

---

src/app/shared/components/fy-connection/fy-connection.component.scss

removed the unwanted changes

---

src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.html
src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.scss

changed the requirements of add more icon and font

changed the requirements of add more icon and font

---

src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.html
src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.scss

Reverts fylein/fyle-mobile-app#1020

Revert "changed the requirements of add more icon and font"

---

src/app/shared/components/expenses-card/expenses-card.component.scss

Reverts fylein/fyle-mobile-app#1019

Revert "8px spacing between merchant and project"

---

src/app/shared/components/fy-connection/fy-connection.component.scss

Reverts fylein/fyle-mobile-app#1018

Revert "removed the unwanted changes"

---

src/app/core/models/v1/expense-fields-map.model.ts
src/app/core/services/expense-fields.service.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.ts

Reverts fylein/fyle-mobile-app#1025

Revert "Category as expense field changes"

---

src/app/fyle/my-create-report/my-create-report.page.ts
src/app/fyle/my-view-report/my-view-report.page.ts
src/app/fyle/my-view-report/resubmit-report-popover/resubmit-report-popover.component.ts
src/app/fyle/my-view-report/submit-report-popover/submit-report-popover.component.ts

Reverts fylein/fyle-mobile-app#1017

Revert "Fixed missing NPS survey triggers in Submit Report Flow."

---

src/app/fyle/dashboard/stats/stats.component.ts
src/app/fyle/my-expenses/my-expenses.page.ts

Reverts fylein/fyle-mobile-app#1041

Revert "Fyle 276nzt2 - Cards should be displayed in the dashboard and my expenses filter even if there aren't any expenses associated with it"

---

src/app/fyle/team-reports/team-report-card/team-report-card.component.scss

fixed payment processing chip on advance report page

fixed payment processing chip on advance report page

---

src/app/fyle/add-edit-expense/add-edit-expense.page.scss

Before:
After:
Error(before):
Error(after):

fixed uneven spacing between Date and category

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.scss

- The more actions three-dot menu button should be shown in `Add mode`

Add expense form header fix

---

src/app/shared/components/expenses-card/expenses-card.component.html
src/app/shared/components/expenses-card/expenses-card.component.ts

changed condition to show project section

changed condition to show project section

---

src/app/auth/sign-in/sign-in.page.ts

Removed multiple requests to access token and updated sign in error message

Fix sign in for mobile app

---

src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts

Could not repro the error, but this pr should fix it

Fix sentry error: `TypeError: Cannot read properties of undefined (reading 'rp_purpose')`

---

src/app/fyle/view-team-advance/view-team-advance.page.html

Name in header section of Team view advance should be View Advance Request and extra advance request should be removed

rename the header name

---

src/app/fyle/view-team-advance/view-team-advance.page.html

Added edit icon in team view advance request page

Added edit icon in team view advance request page

---

src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/shared/components/expenses-card/expenses-card.component.ts
src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.ts

added toast for adding receipts to expenses

added toast for adding receipts to expenses

---

src/app/core/services/sidemenu.service.ts
src/app/fyle/my-create-report/my-create-report.page.html
src/app/fyle/my-edit-report/my-edit-report.page.html
src/app/fyle/my-view-report/submit-report-popover/submit-report-popover.component.html
src/app/shared/components/sidemenu/sidemenu.component.ts

- Removing trips section from sidemenu and add/edit reports
- Removing all trips related routes/pages/popovers and fields/variables inside expenses will be done in the next phase

Remove individual/team trips section from sidemenu and add/edit reports

---

src/app/shared/components/fy-view-attachment/fy-view-attachment.component.html
src/app/shared/components/fy-view-attachment/fy-view-attachment.component.ts

https://user-images.githubusercontent.com/39493102/166927389-72b13f0b-c699-4f52-a06b-366e3e9609be.mp4

Fix multi page pdfs not opening in receipt preview

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.scss

added box-shadow in footer of edit expense page

added box-shadow in footer of edit expense page

---

src/app/core/services/deep-link.service.ts

fixed Cannot read properties of undefined (reading 'split')

fixed Cannot read properties of undefined (reading 'split')

---

src/app/core/services/advance-request.service.ts

fixed Cannot read properties of undefined (reading 'areq_created_at')

fixed Cannot read properties of undefined (reading 'areq_created_at')

---

src/app/fyle/my-view-report/my-view-report.page.ts

Fixed TypeError Cannot read properties of undefined (reading 'rp_currency')

TypeError Cannot read properties of undefined (reading 'rp_currency')

---

src/app/fyle/add-edit-expense/fy-currency/fy-currency.component.scss

changed ratio of currency amount to 30:70

changed ratio of currency amount to 30:70

---

src/app/fyle/dashboard/dashboard.page.html
src/app/fyle/dashboard/dashboard.page.scss

fixed padding of title tasks in tasks page

---

src/app/shared/components/expenses-card/expenses-card.component.ts

fixed Cannot read properties of undefined (reading 'tx_fyle_category')

fixed Cannot read properties of undefined (reading 'tx_fyle_category')

---

src/app/fyle/dashboard/dashboard.page.html
src/app/fyle/dashboard/dashboard.page.scss
src/app/shared/components/fy-number/fy-number.component.scss

-----------------------------------------------------------------------------------------------------------------------------------------

changed the font and color of amount placeholder and text

---

package-lock.json
src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.html
src/app/shared/components/fy-location/fy-location.component.html
src/app/shared/components/fy-location/fy-location.component.ts
src/app/shared/components/fy-multiselect/fy-multiselect.component.html
src/app/shared/components/fy-multiselect/fy-multiselect.component.ts
src/app/shared/components/fy-select/fy-select.component.html
src/app/shared/components/fy-userlist/fy-userlist.component.html
src/app/shared/components/fy-userlist/fy-userlist.component.ts

- Changed placeholder field values from customInput.name -> customInput.placeholder

Fyle 29wgk6a

---

src/app/fyle/add-edit-expense/add-edit-expense.page.scss

aligned the amount error propely

---

src/app/fyle/view-team-report/view-team-report.page.html

fixed payment processing pill in view team report

---

src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/my-add-edit-trip/other-requests/other-requests.component.html
src/app/shared/components/fy-location/fy-location.component.html
src/app/shared/components/fy-location/fy-location.component.ts
src/app/shared/components/fy-multiselect/fy-multiselect.component.html
src/app/shared/components/fy-multiselect/fy-multiselect.component.ts
src/app/shared/components/fy-select/fy-select.component.html
src/app/shared/components/fy-userlist/fy-userlist.component.html
src/app/shared/components/fy-userlist/fy-userlist.component.ts

This reverts commit aa4d16b5d28940bfc1c07522ef2e6fcafa200d35.

Revert "Fyle 29wgk6a (#1095)"

---

ios/App/App/Info.plist
package-lock.json
package.json
src/app/shared/components/capture-receipt/capture-receipt.component.ts

Doc - https://www.npmjs.com/package/@capacitor-community/camera-preview#:~:text=You%20will%20need,microphone%20permission%20request.

Update camera preview plugin - fixes the microphone permission issue in ios

---

src/app/core/models/platform/platform-cost-center.model.ts
src/app/core/services/cost-centers.service.ts

Previously approved PR - https://github.com/fylein/fyle-mobile-app/pull/1115

FYLE-29ptkye-2: Platform changes - Cost center service

---

src/app/core/models/platform/platform-per-diem-rates.model.ts
src/app/core/models/v1/per-diem-rates.model.ts
src/app/core/services/per-diem.service.ts

Previously approved PR - https://github.com/fylein/fyle-mobile-app/pull/1134

FYLE-2dmkmkj-1: Platform changes - Per diem service

---

src/app/fyle/my-view-advance-request/my-view-advance-request.page.scss
src/app/fyle/my-view-advance/my-view-advance.page.scss
src/app/fyle/view-expense/view-expense.page.scss
src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.scss

Fix css warnings

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html

Sentry - https://sentry.io/organizations/fyle-technologies-private-limi/issues/3188192662/?project=5622998&query=is%3Aunresolved
Notes: Ios specific issue in html, not able to repro

Fix sentry error - null is not an object (evaluating 'e.fg.controls.currencyObj.value.orig_currency')

---

src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html

Included critical policy violation condition in the split expense pill

---

src/app/post-verification/invited-user/invited-user.page.ts

Reverts fylein/fyle-mobile-app#1205

Revert "Fix sentry error - Cannot read properties of null (reading 'us')"

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html

Show Add to report option for more than one expense for a report in Reported state

---

src/global.scss

Button opacity fix

---

src/app/shared/components/capture-receipt/capture-receipt.component.scss
src/app/shared/components/capture-receipt/capture-receipt.component.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1s1L2a3S4hp1L2u3Sv2pWm5aoFM4G8JamNZ9Ao6w7p1L2u3ScCrOMAe1Q2u3A4l%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=34UcVp6)
Reverts fylein/fyle-mobile-app#1208

Revert "Reduced load time of capture receipt camera"

---

src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1s1L2a3S4hF7MPQy8Ryu7wdTraki8jxjJLltf9RU2Me1Q2u3A4l%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=alx9XOh)
Reverts fylein/fyle-mobile-app#1226

Revert "Fyle 2a2a8uv: Quick bug fix"

---

src/app/core/services/location.service.ts
src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.html
src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.scss
src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.ts
src/app/shared/components/route-selector/route-selector.component.html
src/app/shared/components/route-selector/route-selector.component.scss
src/app/shared/components/route-selector/route-selector.component.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18Zs1L2a3S4hn2nYalFYp1L2u3St5ffIKIK6lfbA0Mlb8Dwse1Q2u3A4l%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=eMT35UE)
Reverts fylein/fyle-mobile-app#1185

Revert "Fyle 2a2a8uv: Changed Naming conventions for routes in Add mileage"

---

src/app/post-verification/invited-user/invited-user.page.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX195Xs1L2a3S4hR88K9Z8WpcA6e00p1L2u3SnpeVaiqTjSJPIe1Q2u3A4l%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=RZ6B3Ej)

Add optional chaining

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1p1L2u3SX7lSHs1L2a3S4hLK6iOgI408dyD7BCG8v0OaEUOge1Q2u3A4l%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Lv7bcnI)

Fix duplicate info message

---

src/app/shared/components/capture-receipt/capture-receipt.component.scss
src/app/shared/components/capture-receipt/capture-receipt.component.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1s1L2a3S4hkDZBNsRX4UIKs0K9vC6Fba8n3acp1L2u3S0ZS8e1Q2u3A4l%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=8-5Mj0Z)

Capture receipt

---

src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html

Pls refer to this thread for the context: https://fylein.slack.com/archives/C02U2MA2PLN/p1657171648533279

Have only the continue CTA in spender policy violation modal dialog

---

src/app/app.component.ts
src/app/core/services/tracking.service.ts
src/app/fyle/dashboard/stats/stats.component.ts

Trackers to measure app launch time

---

src/app/app.component.ts
src/app/core/services/tracking.service.ts
src/app/fyle/dashboard/stats/stats.component.ts
src/app/shared/components/capture-receipt/capture-receipt.component.ts

Trackers for improve mobile app start up time initiative

---

src/app/fyle/my-view-report/my-view-report.page.html
src/app/fyle/team-reports/team-report-card/team-report-card.component.html
src/app/fyle/team-reports/team-report-card/team-report-card.component.scss

Fixed spacing problems with OMR currency

---

src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts

Per diem fraction amount fix

---

src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.html
src/app/fyle/ccc-classified-actions/ccc-classified-actions.page.scss
src/app/fyle/my-advances/my-advances-card/my-advances-card.component.html
src/app/fyle/my-advances/my-advances-card/my-advances-card.component.scss
src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.scss
src/app/fyle/my-reports/my-reports-card/my-reports-card.component.html
src/app/fyle/my-reports/my-reports-card/my-reports-card.component.scss
src/app/fyle/my-view-report/my-view-report.page.html
src/app/fyle/my-view-report/my-view-report.page.scss
src/app/fyle/team-advance/team-adv-card/team-adv-card.component.html
src/app/fyle/team-advance/team-adv-card/team-adv-card.component.scss
src/app/fyle/team-reports/team-report-card/team-report-card.component.html
src/app/fyle/team-reports/team-report-card/team-report-card.component.scss
src/app/fyle/view-expense/view-expense.page.html
src/app/fyle/view-expense/view-expense.page.scss
src/app/fyle/view-mileage/view-mileage.page.html
src/app/fyle/view-mileage/view-mileage.page.scss
src/app/fyle/view-per-diem/view-per-diem.page.html
src/app/fyle/view-per-diem/view-per-diem.page.scss
src/app/fyle/view-team-report/view-team-report.page.html
src/app/fyle/view-team-report/view-team-report.page.scss
src/app/shared/components/expenses-card/expenses-card.component.html
src/app/shared/components/expenses-card/expenses-card.component.scss
src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.html
src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.scss
src/app/shared/components/summary-tile/summary-tile.component.html
src/app/shared/components/summary-tile/summary-tile.component.scss
src/global.scss
src/theme/colors.scss

updated pills:
comments fixes:

pill color changes in mobile-app

---

src/app/shared/components/bank-account-cards/bank-account-cards.component.ts

https://sentry.io/organizations/fyle-technologies-private-limi/issues/3392215821/?project=5622998&referrer=slack
https://fylein.slack.com/archives/CT9R2TGQ3/p1660183379155379

Fix for Cannot read properties of undefined (reading 'id') sentry error

---

src/app/core/models/vendor.model.ts
src/app/shared/components/fy-select-vendor/fy-select-modal/fy-select-vendor-modal.component.html
src/app/shared/components/fy-select-vendor/fy-select-modal/fy-select-vendor-modal.component.scss
src/app/shared/components/fy-select-vendor/fy-select-modal/fy-select-vendor-modal.component.ts

Adding virtual scroll in the vendor modal component

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html

FYLE-2rhkbj0: Using virtual scroll component for cost center modal

---

src/app/core/services/tasks.service.ts
src/app/fyle/dashboard/stats/stats.component.ts
src/app/fyle/dashboard/tasks/tasks.component.ts

- TypeError: Cannot read properties of null (reading 'corporate_credit_card_settings')
- TypeError: Cannot read properties of null (reading 'length')
- TypeError: Cannot read properties of null (reading 'approval_settings')
https://sentry.io/organizations/fyle-technologies-private-limi/issues/3409776814/?project=5622998&query=is%3Aunresolved&statsPeriod=14d

Sentry fixes in dashboard and tasks pages

---

src/app/core/services/launch-darkly.service.ts

Reverts fylein/fyle-mobile-app#1319

Revert "Adding launch darkly method to fetch the `fix_implicit_merge` key"

---

src/app/fyle/corporate-card-expenses/corporate-card-expenses.page.ts
src/app/fyle/dashboard/tasks/tasks.component.ts
src/app/fyle/my-advances/my-advances.page.ts
src/app/fyle/my-expenses/my-expenses.page.ts
src/app/fyle/my-reports/my-reports.page.ts
src/app/fyle/personal-cards/personal-cards.page.ts
src/app/fyle/team-advance/team-advance.page.ts
src/app/fyle/team-reports/team-reports.page.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX184u2ITfFUXYmLgGdVsVD7xxCVlOuk8%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=gWqzw4B)
https://sentry.io/organizations/fyle-technologies-private-limi/issues/3552161516/?project=5622998&query=is%3Aunresolved&statsPeriod=14d

Added fix for sentry issue

---

src/app/fyle/view-team-report/view-team-report.page.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX15dj4e9o6qJ4otnhTFlLV2b54oDxydA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=KS_aroc)
https://sentry.io/organizations/fyle-technologies-private-limi/issues/3386938812/?project=5622998&query=is%3Aunresolved&statsPeriod=14d

Added fix for sentry issue around reduce

---

src/app/shared/components/route-selector/route-selector.component.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1nHiEc5YQ1s3fj4QC92EA1ttVDHOP1AVE%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=tO7FXAL)
https://sentry.io/organizations/fyle-technologies-private-limi/issues/3389805466/?project=5622998&query=is%3Aunresolved&statsPeriod=7d#exception

Added more fixes

---

src/app/fyle/my-create-report/my-create-report.page.ts
src/app/shared/components/create-new-report/create-new-report.component.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18aKhbIBJuegVHebIXybUiovx4d3JijrU%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=F527dpz)
https://sentry.io/organizations/fyle-technologies-private-limi/issues/3562313600/?project=5622998&query=is%3Aunresolved&statsPeriod=7d

Silly sentry report issue

---

src/app/core/services/org-user.service.ts
src/app/fyle/delegated-accounts/delegated-accounts.page.ts
src/app/shared/components/sidemenu/sidemenu.component.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19h2AFaPUGg7DRBjVl4Mt4fo4bGZvWxcw%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=D6xweMr)
https://sentry.io/organizations/fyle-technologies-private-limi/issues/3461008869/?project=5622998&query=is%3Aunresolved

Fixed sentry issue around delegatee

---

src/app/core/services/accounts.service.ts
src/app/core/services/org-user-settings.service.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/shared/components/virtual-select/virtual-select-modal/virtual-select-modal.component.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX17mxgq6RheWASaq8TXUZlrGJPCPm8QqCw%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=xr51ALr)

Added more changes

---

src/app/core/services/launch-darkly.service.ts
src/app/core/services/report.service.ts
src/app/core/services/tasks.service.ts
src/app/core/services/tracking.service.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
src/app/fyle/dashboard/tasks/auto-submission-info-card/auto-submission-info-card.component.html
src/app/fyle/dashboard/tasks/auto-submission-info-card/auto-submission-info-card.component.ts
src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.html
src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.ts
src/app/fyle/dashboard/tasks/tasks.component.html
src/app/fyle/dashboard/tasks/tasks.component.ts
src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.html
src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
src/theme/colors.scss

Changes in this PR
- Added LD support
- Content change in add to report list view - Removed state pill and updated text
New design

#automate_report_submission: Add LD flag in expense form and tasks page

---

src/app/core/models/report-auto-submission-details.model.ts
src/app/core/services/launch-darkly.service.ts
src/app/core/services/report.service.ts
src/app/core/services/spender-platform-api.service.ts
src/app/core/services/tasks.service.ts
src/app/core/services/tracking.service.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
src/app/fyle/dashboard/tasks/auto-submission-info-card/auto-submission-info-card.component.html
src/app/fyle/dashboard/tasks/auto-submission-info-card/auto-submission-info-card.component.scss
src/app/fyle/dashboard/tasks/auto-submission-info-card/auto-submission-info-card.component.spec.ts
src/app/fyle/dashboard/tasks/auto-submission-info-card/auto-submission-info-card.component.ts
src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.html
src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.ts
src/app/fyle/dashboard/tasks/tasks.component.html
src/app/fyle/dashboard/tasks/tasks.component.scss
src/app/fyle/dashboard/tasks/tasks.component.ts
src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.html
src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.scss
src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.ts
src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
src/app/shared/shared.module.ts
src/global.scss
src/theme/colors.scss

Combined changes from these approved PRs
- https://github.com/fylein/fyle-mobile-app/pull/1315
- https://github.com/fylein/fyle-mobile-app/pull/1317
- https://github.com/fylein/fyle-mobile-app/pull/1323
- https://github.com/fylein/fyle-mobile-app/pull/1327
- https://github.com/fylein/fyle-mobile-app/pull/1346

#automate_report_submission: combined changes

---

src/app/fyle/dashboard/tasks/tasks.component.scss
src/app/fyle/my-expenses/my-expenses.page.scss

Changed the filter pills bg from transparent to solid

---

src/app/auth/sign-in/sign-in.page.ts
src/app/auth/switch-org/switch-org.page.ts
src/app/core/services/tracking.service.ts

Tracking switch org launch time

---

src/app/shared/components/capture-receipt/capture-receipt.component.ts

Slack thread - https://fylein.slack.com/archives/C017C400V37/p1663687817962339?thread_ts=1663687522.278129&cid=C017C400V37

#payment_mode_configurations - Fixes error where instafyle was failing in offline mode

---

src/app/auth/sign-in/sign-in.page.ts

Sentry link - https://sentry.io/organizations/fyle-technologies-private-limi/issues/2222706032/?project=5622998
This error occurs when user enters incorrect email/passoword. Since we dont want sentry to report such errors, we should handle it when we subscribe to the observable.
Also updated deprecated rxjs syntax

#mission_nps_mobile_40: Fix signin sentry error and remove deprecated syntax

---

src/app/auth/pending-verification/pending-verification.page.ts
src/app/auth/reset-password/reset-password.page.ts
src/app/auth/verify/verify.page.ts

Sentry link - https://sentry.io/organizations/fyle-technologies-private-limi/issues/2224304099/events/3ef96aff4de9477489869409c6d14a7a/?project=5622998

#mission_nps_mobile_40: Handle errors in pending verification, reset password page

---

src/app/core/services/merge-expenses.service.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts

No errors, things are working fine, 
added this fail-safe just in case the id is null/undefined

Added fail safe

---

src/app/core/services/categories.service.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/merge-expense/merge-expense.page.html
src/app/fyle/merge-expense/merge-expense.page.ts
src/app/fyle/view-expense/view-expense.page.html
src/app/fyle/view-expense/view-expense.page.ts
src/app/shared/components/fy-category-icon/fy-category-icon.component.html

[https://www.notion.so/fyleuniverse/Mobile-app-mcc_v1_and_category_cleanup-48da37baaa954c0d96cc3793e6fd6289](url)

Adding new system categories - Airlines, Courier & Lodging

---

src/app/core/services/tasks.service.ts
src/app/fyle/dashboard/tasks/tasks.component.ts

The name of the filter was given as Draft which has been deprecated, changed it to Incomplete in this fix

Task Filter Bug Fix

---

src/app/core/services/tasks.service.ts
src/app/fyle/dashboard/tasks/tasks.component.ts

Reverts fylein/fyle-mobile-app#1410

Revert "Task Filter Bug Fix"

---

src/app/fyle/my-create-report/my-create-report.page.html
src/app/fyle/my-create-report/my-create-report.page.ts
src/app/fyle/my-view-report/my-view-report.page.html

The draft button would be active and allow to create a report even if the report title is empty

Draft Button Bug Fix

---

src/app/core/services/payment-modes.service.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
src/app/fyle/view-expense/view-expense.page.html
src/app/fyle/view-expense/view-expense.page.ts
src/app/fyle/view-mileage/view-mileage.page.html
src/app/fyle/view-mileage/view-mileage.page.ts
src/app/fyle/view-per-diem/view-per-diem.page.html
src/app/fyle/view-per-diem/view-per-diem.page.ts

Removed logic for hiding payment mode in add/edit/view expense forms

#payment_mode_configurations: Never hide payment mode

---

src/app/core/models/platform/platform-policy-expense.model.ts
src/app/core/models/public-policy-expense.model.ts
src/app/core/models/public-policy-transaction.model.ts
src/app/core/services/policy.service.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX195J5vnVzc3hRs65Bl54Yp3daubM0WyVbc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=6rMD0L9)

Transformation function for /check_policies

---

src/app/fyle/add-edit-expense/add-edit-expense.page.ts

Reverts fylein/fyle-mobile-app#1436

Revert "Default select of report"

---

src/app/core/models/platform/platform-check-expense-policy.model.ts
src/app/core/models/platform/platform-expense-policy.model.ts
src/app/core/models/platform/platform-final-expense-policy-state.model.ts
src/app/core/models/platform/platform-individual-expense-policy-state.model.ts
src/app/core/services/policy.service.ts
src/app/core/services/transaction.service.ts
src/app/shared/components/fy-policy-violation/fy-policy-violation.component.html
src/app/shared/components/fy-policy-violation/fy-policy-violation.component.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1RoxuAL99HyDW4hNrruZ0Ci3Gg9BRX04%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=7484Ucj)

Functions to accomodate check policies call

---

src/app/fyle/add-edit-expense/add-edit-expense.page.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1TsxhJDYlSbLrWNYePRK60s7RWSkv90k%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=BeHcB8Q)

Replace /policy/test with /check_policies in add edit expense page

---

src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19uYQe7QF82pVmGRa5xfdjHyYDz4mms%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=2eHRsgm)

Replace /policy/test with /check_policies in add edit mileage page

---

src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX15cpDGsHE5RdZ9H8iFZr9afrQB5vzjxOE%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=tD-sonq)

Replace /policy/test with /check_policies in add edit per diem page

---

src/app/core/services/transactions-outbox.service.ts
src/app/shared/components/capture-receipt/capture-receipt.component.html
src/app/shared/components/capture-receipt/capture-receipt.component.scss
src/app/shared/components/capture-receipt/capture-receipt.component.ts
src/app/shared/components/toast-message/toast-message.component.html
src/global.scss

UI when camera opened for the 4th time:
https://user-images.githubusercontent.com/39493102/200512391-f8485e76-b742-46fd-bd0a-edcf33a49404.mp4
UI Preview:

#mission_nps_mobile_40: Prompt user to use bulkfyle after using instafyle thrice

---

src/app/app.component.ts
src/app/auth/app-version/app-version.page.ts
src/app/core/models/back-button-action-priority.enum.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
src/app/fyle/my-expenses/my-expenses.page.ts
src/app/shared/components/capture-receipt/crop-receipt/crop-receipt.component.ts
src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.ts

Notion Doc - https://www.notion.so/fyleuniverse/Fix-Android-Hardware-Back-button-97f533f2a020485db9239bcbf1eda7cc

#mission_nps_mobile_40: Fix hardware back button redirections in android app

---

src/app/core/models/platform/platform-policy-expense.model.ts
src/app/core/services/policy.service.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1TxWN2NwsPsh9o1U1xUquDWmw90KW3E%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=UPl2Jse)
This PR contains bug fixes and implementation changes with respect to a bug encountered while testing in https://github.com/fylein/fyle-mobile-app/pull/1466

Implementation fixes

---

src/app/core/models/approval.model.ts
src/app/core/models/extended_advance_request.model.ts
src/app/core/models/extended_status.model.ts
src/app/core/models/file.model.ts
src/app/core/models/file_obj.model.ts
src/app/core/models/transaction-status.model.ts
src/app/core/services/permissions.service.ts
src/app/core/services/status.service.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1aWXjBbgQkbCIqmlEAuumWlEL8JTRZqU%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=1Y4aMPK)

trips, hotel and transportations related code removed

---

src/app/core/models/filters.model.ts
src/app/core/services/filters-helper.service.spec.ts
src/app/core/services/filters-helper.service.ts

Edit 1: The code coverage is now accurate
Edit 2: Code coverage improved
The code coverage is now close to 95%
Edit 3: Code coverage now 100%

Code Coverage: Filters-Helper Service

---

src/app/core/services/policy.service.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1TugL2TitdM9GmjRdQ4Ry3MPYRkbnfcvM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=hsyctOc)

Instafyle bypass policy 400

---

src/app/shared/components/fy-category-icon/fy-category-icon.component.html

The icon for now will be the default icon, once received from the design team, this will be updated

Added new system categories icons for `Rental` and `Groceries`

---

package.json
src/app/core/services/transaction.service.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts

https://user-images.githubusercontent.com/39493102/202455037-3b8dc1df-eda2-4c39-a917-24548dc49c89.mov

#mission_nps_mobile_40: Fix redirection after expense is removed from report

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.scss

Reverts fylein/fyle-mobile-app#1472

Revert "Info Box In Review Expenses"

---

src/app/core/services/launch-darkly.service.ts
src/app/core/services/payment-modes.service.ts
src/app/core/services/report.service.ts

https://app.clickup.com/t/30k7g3x
https://app.clickup.com/t/30k7ewy

Remove LD flag for payment_mode_configurations and automated report submissions

---

src/app/core/services/report.service.ts
src/app/fyle/my-view-report/my-view-report.page.html
src/app/fyle/my-view-report/my-view-report.page.ts

This PR has changes from an approved PR - #1511 
Messed up something when changing the base branch, so cherry-picked my changes in this branch.

#mission_nps_mobile_40: Fix view report page not updating after adding expenses to report

---

src/app/fyle/add-edit-expense/add-edit-expense.page.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1GSpB7XO7rB780oKezryPpZfV5JEtCOg%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=O6GAJlV)

Fix: Expense category patch in update case

---

angular.json

FYLE-31v8k3u: Remove tracking service from code coverage

---

src/app/fyle/add-edit-expense/add-edit-expense.page.ts

BR Link - https://app.clickup.com/t/85zrgjjrg

Add failsafe if category field does not have a fyle_category

---

package-lock.json
src/app/app-routing.module.ts
src/app/fyle/dashboard/dashboard.page.ts
src/app/fyle/dashboard/stats/stats.component.ts
src/app/fyle/dashboard/tasks/tasks.component.ts
src/app/fyle/my-expenses/my-expenses.page.ts
src/app/shared/components/expenses-card/expenses-card.component.ts

Reverts fylein/fyle-mobile-app#1550

Revert "Removed memory leaks in my expenses page"

---

src/app/auth/switch-org/switch-org.page.ts
src/app/core/models/resend-email-verification.model.ts
src/app/core/services/auth.service.ts

Reverts fylein/fyle-mobile-app#1426

Revert "Fyle 2wuxjb5"

---

src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/my-view-report/my-view-report.page.ts
src/app/shared/components/expenses-card/expenses-card.component.ts

Sentry:
- https://sentry.io/organizations/fyle-technologies-private-limi/issues/3818312761/?project=5622998&referrer=release-issue-stream
- https://sentry.io/organizations/fyle-technologies-private-limi/issues/3823109612/?project=5622998&referrer=release-issue-stream
-Trackers added to get data on heic receipts uploaded

Fix sentry issue and add trackers for uploaded file type

---

src/app/core/models/platform/platform-policy-expense.model.ts
src/app/core/services/policy.service.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1wxq7n2V5J9YuOe9yyh6AoVaD5l7o5pA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Hmcg3l2)

Fix: Null array throws 400 in expense creation flow

---

src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
src/app/fyle/my-view-report/my-view-report.page.html

Fixes this sentry issue: https://sentry.io/organizations/fyle-technologies-private-limi/issues/3835941711/?project=5622998&referrer=release-issue-stream
This check was missed in case of resubmit report.

Fix report page issue

---

src/app/auth/switch-org/switch-org.page.ts

Clickup Task: https://app.clickup.com/t/85zrh6cgx
Sentry issues thats been fixed:
1) https://sentry.io/organizations/fyle-technologies-private-limi/issues/3840499445/?project=5622998&referrer=release-issue-stream
2) https://sentry.io/organizations/fyle-technologies-private-limi/issues/3836338631/?project=5622998&referrer=release-issue-stream

fixes for the sentry issues

---

src/app/core/services/transaction.service.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.ts

Content Changes for fix_implicit_merge_errors

---

src/app/core/services/transaction.service.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.ts

Reverts fylein/fyle-mobile-app#1579

Revert "Content Changes for fix_implicit_merge_errors"

---

src/app/core/services/org-user.service.ts

- Removed unused methods in the org user service

Code coverage: Org user service - 1

---

src/app/core/services/status.service.ts

@Dimple16 
The Audit header trails **before** :
The Updated Audit header trails:
Changed File : ```src\app\core\services\status.service.ts```

 task  FYLE-85zrh6q1u , Audit trails header should be 'Expense Added to Report' 

---

src/app/fyle/dashboard/dashboard.service.spec.ts

The testing bench has been setup ready to write tests.

Code Coverage for Dashboard Service

---

src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.scss
src/global.scss

task 20d8kmq Create Expense: Mileage expense: Select location pop up.~ There should be some top spacing

---

src/app/core/services/status.service.ts

task 85zrja2pd Header changed to `Report Submitted` in reports audit trail

---

src/app/core/services/transaction.service.spec.ts

- Checked if there are any unused methods
- Added initial test file setup changes

Code coverage: Transaction service - subtasks 1&2

---

src/app/core/models/expense.model.ts
src/app/core/services/report.service.ts

Removed unused code from report service and added params and return types for some functions

Code coverage: Report Service #2

---

src/app/core/models/currency-summary.model.ts
src/app/core/models/etxn-params.model.ts
src/app/core/models/filter-query-params.model.ts
src/app/core/models/payment-mode-summary.model.ts
src/app/core/models/sort-filters-params.model.ts
src/app/core/models/v1/transaction.model.ts
src/app/core/models/v2/api-v2-response.model.ts
src/app/core/services/transaction.service.ts
src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts

- Added missing models
- Added param and return types for all methods

Code coverage: Transaction service - Subtask-3

---

src/app/fyle/my-view-report/my-view-report.page.html
src/app/fyle/my-view-report/my-view-report.page.ts

 FYLE-21fmba1 Removed the resubmit report pop up

---

src/app/core/services/snackbar-properties.service.spec.ts

Code Coverage subtask 85zrja8dj : Snackbar properties service

---

src/app/core/services/modal-properties.service.spec.ts
src/app/core/services/modal-properties.service.ts

Code Coverage subtask 85zrja31j: Modal properties service

---

src/app/shared/pipes/mileage-rate-name.pipe.spec.ts

FYLE-85zrk1n0c Code coverage: Mileage Rate Name pipe

---

src/app/fyle/my-create-report/my-create-report.page.html
src/app/fyle/my-create-report/my-create-report.page.scss
src/app/fyle/my-create-report/my-create-report.page.ts

Slack thread - https://fylein.slack.com/archives/C017C400V37/p1675233681825619
Before:
After:

Hide Add expense button on create report page and fix zero state alignment

---

src/app/shared/components/fy-highlight-text/fy-highlight-text.component.scss
src/app/shared/pipes/highlight.pipe.spec.ts

Fyle 85zrmb5uq Code Coverage : Highlight Pipe

---

src/app/core/mock-data/data-transform.data.ts

A fix for a test failing on master

Date Fix for Report Service

---

src/app/core/mock-data/org-settings.data.ts
src/app/core/mock-data/sidemenu-allowed-actions.data.ts
src/app/core/models/sidemenu-allowed-actions.model.ts
src/app/core/services/sidemenu.service.spec.ts
src/app/core/services/sidemenu.service.ts

Code coverage: Sidemenu service 100%

---

src/app/shared/components/view-expense-skeleton-loader/view-expense-skeleton-loader.component.spec.ts

Note: I'll raise another PR with more test cases related to the template file

Code coverage: View expense skeleton loader component - ts file 100%

---

src/app/fyle/add-edit-expense/add-edit-expense.page.ts

BR Link: https://app.clickup.com/t/85zrmtpf1

BR: Fix issue in custom fields page

---

src/app/shared/pipes/humanize-currency.pipe.spec.ts
src/app/shared/pipes/humanize-currency.pipe.ts

Code Coverage: Humanize Currency

---

src/app/core/services/org.service.spec.ts
src/app/core/services/org.service.ts

Code coverage: Org service - Added return types + 28.57% statements coverage

---

src/app/core/mock-data/currency-ip.data.ts
src/app/core/models/currency-ip.model.ts
src/app/core/services/org.service.spec.ts

Note: Ignoring a `catchError` coverage

Code coverage: Org service - overall %

---

src/app/shared/components/fy-highlight-text/fy-highlight-text.component.spec.ts

Code coverage: FyHighlightText Component - 100%

---

src/app/core/mock-data/advance-request-approver.data.ts
src/app/shared/components/fy-highlight-text/fy-highlight-text.component.spec.ts
src/app/shared/components/summary-tile/summary-tile.component.spec.ts
src/app/shared/components/summary-tile/summary-tile.component.ts
src/app/shared/components/view-expense-skeleton-loader/view-expense-skeleton-loader.component.spec.ts

Code coverage: Summary tile component - 100%

---

src/app/core/mock-data/location.data.ts
src/app/core/models/location.model.ts
src/app/core/services/mileage.service.spec.ts
src/app/core/services/mileage.service.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts

Code Coverage: Mileage Service #1

---

src/app/core/dom-helpers.ts
src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.spec.ts

Code coverage: Sidemenu header component - 100%

---

src/app/core/dom-helpers.ts
src/app/fyle/dashboard/tasks/auto-submission-info-card/auto-submission-info-card.component.spec.ts

Code coverage: AutoSubmissionInfoCardComponent - 100%

---

src/app/core/dom-helpers.ts
src/app/shared/components/comments-history/audit-history/statuses-diff/statuses-diff.component.spec.ts
src/app/shared/components/fy-loading-screen/fy-loading-screen.component.spec.ts

Code coverage: FyLoadingScreen Component - 100%

---

src/app/core/services/currency.service.spec.ts
src/app/core/services/user-event.service.spec.ts
src/app/core/services/user-event.service.ts

Code coverage: User event service - 100%

---

src/app/core/services/jwt-helper.service.spec.ts

Code coverage: JwtHelper Service - 100%

---

src/app/core/services/loader.service.spec.ts

Code coverage: Loader service - 100%

---

.github/workflows/manual-appflow-1.yml
.github/workflows/manual-appflow-with-inputs.yml
.npmrc
package-lock.json
package.json

Appflow github action ref - https://github.com/ionic-team/appflow-build/blob/main/action.yml

Restrict node version

---

src/app/core/services/transactions-outbox.service.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
src/app/shared/components/capture-receipt/capture-receipt.component.ts

This Pr removes API calls which breaks the app in offline mode
Slack thread - https://fylein.slack.com/archives/C017C400V37/p1676536099990249

Fix offline mode 

---

src/app/core/services/storage.service.spec.ts

Code coverage: Storage service - 100%

---

src/app/core/mock-data/file-object.data.ts
src/app/core/models/file-obj.model.ts
src/app/core/services/file.service.spec.ts
src/app/core/services/file.service.ts

Code coverage: File service - Initial changes

---

src/app/core/mock-data/advance-request-actions.data.ts
src/app/core/mock-data/extended-advance-request.data.ts
src/app/core/models/extended_advance_request.model.ts
src/app/core/services/advance-request.service.spec.ts

Code Coverage: Advance Request Service #1

---

src/app/auth/app-version/app-version.page.spec.ts

Code coverage: App version page component - changes-1

---

src/app/auth/sign-in/error/error.component.html
src/app/auth/sign-in/error/error.component.spec.ts
src/app/auth/sign-in/error/error.component.ts

Code coverage: Sign in error component - 100%

---

src/app/auth/disabled/disabled.page.spec.ts

Code coverage: Disabled page component - 100%

---

src/app/shared/components/bank-account-cards/bank-account-card/delete-button/delete-button.component.spec.ts

Code coverage: Bank account card DeleteButton Component - 100%

---

src/app/core/mock-data/org-settings.data.ts
src/app/core/mock-data/org-user-settings.data.ts
src/app/core/services/payment-modes.service.spec.ts
src/app/core/services/payment-modes.service.ts

Code Coverage: Payment Mode Service #1

---

src/app/fyle/merge-expense/card-transaction-preview/card-transaction-preview.component.html
src/app/fyle/merge-expense/card-transaction-preview/card-transaction-preview.component.spec.ts

Code coverage: CardTransactionPreview Component - 100%

---

src/app/core/services/popup.service.spec.ts

Code Coverage: Popup Service #1

---

src/app/shared/components/fy-category-icon/fy-category-icon.component.spec.ts
src/app/shared/components/fy-category-icon/fy-category-icon.component.ts

Note: I haven't added any specific test case for template as such since this is only display of icons

Code coverage: FyCategoryIcon Component - 100%

---

src/app/core/mock-data/filter.data.ts
src/app/core/mock-data/personal-cards.data.ts
src/app/core/mock-data/selected-filters.data.ts
src/app/core/models/personal-card-filters.model.ts
src/app/core/services/personal-cards.service.spec.ts
src/app/core/services/personal-cards.service.ts

Code Coverage: Personal Card #2

---

src/app/core/services/invitation-requests.service.spec.ts

Fyle 85zrnrbyr Code Coverage 100% : Invitation Requests Service

---

src/app/core/services/dependent-fields.service.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
src/app/shared/components/dependent-field/dependent-field-modal/dependent-field-modal.component.html
src/app/shared/components/dependent-field/dependent-field-modal/dependent-field-modal.component.ts
src/app/shared/components/dependent-field/dependent-field.component.ts

- Fix title of dependent fields modal and remove unused inputs
- Fix edit expense when project has an unfilled dependent field
- Cache dependent fields values call

Dependent Fields: Fix more bugs

---

.github/workflows/pr-checks-config.yml
.github/workflows/pr-checks.yml

Clickup - https://app.clickup.com/t/85zrr5mpt

feat: Add PR checks

---

src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts

https://app.clickup.com/t/2zb70qu

feat: Persist Show More in add mileage and add perdiem

---

src/app/core/services/location.service.spec.ts

ClickUp : https://app.clickup.com/t/85zrrc24m

test: Location Service 50% coverage

---

src/app/core/mock-data/auth-reponse.data.ts
src/app/core/models/auth-response.model.ts
src/app/core/services/google-auth.service.spec.ts

test: Code Coverage: Google Auth Service #1

---

src/app/core/mock-data/org-payment-mode-settings.data.ts
src/app/core/services/payment-modes.service.spec.ts

https://app.clickup.com/t/85zrpcyvg
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX188zIyhicb4MeTYacvqYW6GzAwdSd3S0E%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=suAnRjX)

fix:Tests for service function isNonReimbursableOrg()

---

src/app/core/services/token.service.spec.ts

click up - https://app.clickup.com/t/85zrpu3mx

test: Code coverage - Token service - 100% branches

---

src/app/core/mock-data/data-transform.data.ts
src/app/core/services/data-transform.service.spec.ts

ClickUp: https://app.clickup.com/t/85zrpv6b8

test: Code coverage 100% data transform service

---

src/app/core/services/permissions.service.spec.ts
src/app/core/services/permissions.service.ts

test: Code Coverage: Permission Service

---

src/app/core/services/accounts.service.spec.ts
src/app/core/test-data/accounts.service.spec.data.ts

click up: https://app.clickup.com/t/85zrpjfr0
context: https://github.com/fylein/fyle-mobile-app/pull/1737
slack thread: https://fylein.slack.com/archives/CN40C97P0/p1677664044379079

test: Added test for an old issue in accounts service

---

src/app/core/dom-helpers.ts
src/app/fyle/my-view-report/edit-report-name-popover/edit-report-name-popover.component.html
src/app/fyle/my-view-report/edit-report-name-popover/edit-report-name-popover.component.spec.ts

click up - https://app.clickup.com/t/85zrrpeju

test: Code coverage: EditReportNamePopover Component - 100%

---

src/app/auth/switch-org/active-org-card/active-org-card.component.spec.ts

test: Code Coverage: Active Org Card Component

---

src/app/shared/components/fy-header/fy-header.component.spec.ts

test: Code Coverage: Fy-Header Component

---

src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts

Clickup - https://app.clickup.com/t/85zrt3tg5
- Fixed this for add/edit expense forms and tested on staging 🍏 
- This doesnt change anything in view/merge expenses ✔️

fix: Dependent fields: Send projectv2_name to api when getting dependent firlds

---

src/app/auth/switch-org/active-org-card/active-org-card.component.spec.ts

Import added for `IonicModule ` in the **ActiveOrgCardComponent** spec file

fix: Active Org Card Component

---

src/app/shared/components/fy-connection/fy-connection.component.spec.ts

clickUp: https://app.clickup.com/t/85zrpv3z4

test: FyConnection Comppnent 100% coverage

---

src/app/core/services/config.service.spec.ts

test: Code Coverage : Config Service 100%

---

src/app/core/services/refiner.service.spec.ts

test: Code coverage Refiner Service 67%

---

src/app/core/services/date.service.spec.ts
src/app/core/services/login-info.service.spec.ts
src/app/core/services/login-info.service.ts

test: Code Coverage: Log Info Service #1

---

src/app/fyle/my-reports/my-reports.page.ts
src/app/fyle/team-reports/team-reports.page.ts
src/app/shared/components/fy-filters/filter-options.interface.ts
src/app/shared/components/fy-filters/fy-filters.component.html
src/app/shared/components/fy-filters/fy-filters.component.scss
src/app/shared/components/fy-filters/fy-filters.component.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1GjHeHRRmdRxTnKfnqB0nqBKybK3GvBg%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=CgRfspq)
Loom recording staging: https://www.loom.com/share/58b98f0ff9804afdb46c6a7a64c09ea8

State name changes for filter options || Simplified Report Closure

---

src/app/core/services/secure-storage.service.spec.ts

click up - https://app.clickup.com/t/85zrpu62m
Note: This service uses a capacitor plugin. I'm not mocking the plugin implementation since that wouldn't add much value.

test: Code coverage: Secure storage service - Initial changes

---

src/app/shared/components/capture-receipt/add-more-popup/add-more-popup.component.spec.ts

test: Code coverage add more popup component 100%

---

src/app/shared/components/navigation-footer/fy-nav-footer/fy-nav-footer.component.spec.ts

click up - https://app.clickup.com/t/85zrt3p3u

test: Code coverage: FyNavFooter Component - 100%

---

src/app/fyle/view-team-report/view-team-report-etxn-card/view-team-report-etxn-card.component.spec.ts

test: Code Coverage: View Team Report ETXN Card Component

---

src/app/fyle/add-edit-advance-request/policy-violation-dialog/policy-violation-dialog.component.spec.ts

test: Code Coverage Policy Violation Dialog 100%

---

.github/workflows/internal-release.yml

Clickup - https://app.clickup.com/t/85zrrkgva

feat: Github action to trigger prod internal release

---

src/app/core/services/gmaps.service.spec.ts

click up - https://app.clickup.com/t/85zrthz68

test: Code coverage: Gmaps Service - Initial test

---

src/app/core/mock-data/ld-all-flags.data.ts
src/app/core/mock-data/ld-client-user.data.ts
src/app/core/services/launch-darkly.service.spec.ts

test: Code Coverage: Launch Darkly Service

---

src/app/shared/components/toast-message/toast-message.component.spec.ts

test: Code coverage 100% Toast-message component 

---

src/app/fyle/add-edit-advance-request/policy-violation-dialog/policy-violation-dialog.component.spec.ts

fix: Added imports to avoid warnings Policy Violation Dialog component

---

src/app/core/services/launch-darkly.service.spec.ts

fix: Code Coverage: Launch Darkly Service #2

---

src/app/core/services/network.service.spec.ts

test: Code Coverage: Network Service 

---

src/app/core/mock-data/extended-device-info.data.ts
src/app/core/services/smartlook.service.spec.ts

click up - https://app.clickup.com/t/85zrt3mz0

test: Code coverage: Smartlook Service

---

src/app/core/services/timezone.service.spec.ts
src/app/core/services/timezone.service.ts

clickUp: https://app.clickup.com/t/85zrtnvuk

test: Code coverage 63% Timezone service 

---

src/app/auth/sign-in/sign-in.page.ts
src/app/core/services/custom-inputs.service.ts
src/app/core/services/popup.service.ts
src/app/core/services/projects.service.ts
src/app/fyle/add-edit-advance-request/fy-currency/fy-currency-choose-currency/fy-currency-choose-currency.component.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/merge-expense/merge-expense.page.ts
src/app/fyle/my-create-report/my-create-report.page.ts
src/app/fyle/my-view-report/my-view-report.page.ts
src/app/fyle/view-team-report/view-team-report.page.ts
src/app/shared/components/capture-receipt/capture-receipt.component.ts
src/app/shared/components/expenses-card/expenses-card.component.html

Clickup - https://app.clickup.com/t/85zrtvb8u

fix: Fix some sentry issues

---

src/app/core/services/timezone.service.spec.ts

clickUp: https://app.clickup.com/t/85zrtyg5w

test:  Code Coverage Timezone Service 93%

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/shared/components/dependent-fields/dependent-fields.component.html
src/app/shared/components/dependent-fields/dependent-fields.component.ts

Clickup - https://app.clickup.com/t/85zrrve55

feat: Dependent Fields: Refactoring

---

src/app/core/services/tracking.service.ts
src/app/fyle/dashboard/dashboard.page.ts
src/app/fyle/my-advances/my-advances.page.ts
src/app/fyle/my-expenses/my-expenses.page.ts
src/app/fyle/my-reports/my-reports.page.ts
src/app/fyle/personal-cards/personal-cards.page.ts
src/app/fyle/team-advance/team-advance.page.ts
src/app/fyle/team-reports/team-reports.page.ts
src/app/shared/components/fy-header/fy-header.component.spec.ts
src/app/shared/components/fy-menu-icon/fy-menu-icon.component.html
src/app/shared/components/fy-menu-icon/fy-menu-icon.component.spec.ts
src/app/shared/components/fy-menu-icon/fy-menu-icon.component.ts
src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.ts

Clickup: https://app.clickup.com/t/85zrtybcb

feat: Add trackers for sidemenu and home tab

---

src/app/core/services/transactions-outbox.service.spec.ts
src/app/core/services/transactions-outbox.service.ts

click up - https://app.clickup.com/t/85zrt3n2j

test: Code coverage: Transaction outbox service - PR-1

---

src/app/core/mock-data/app-version.data.ts
src/app/core/services/app-version.service.spec.ts
src/app/core/services/app-version.service.ts

test: Code Coverage: App Version Service

---

src/app/core/services/fresh-chat.service.spec.ts

test: Code Coverage: Fresh Chat Service

---

src/app/core/services/transactions-outbox.service.spec.ts

click up - https://app.clickup.com/t/85zru677k

test: Code coverage: Transaction outbox service - changes-2

---

.github/workflows/create-release-branch.yml

Clickup - https://app.clickup.com/t/85zru3cqk
Tested in my personal repo with manual dispatch and running the job every 5 mins. Both worked fine 🟢

feat: Create release branch automatically every friday at 5 PM

---

src/app/shared/components/fy-zero-state/fy-zero-state.component.spec.ts

test: Code Coverage: Fy-Zero State Component

---

src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.spec.ts

test: Code Coverage: Fy-Critical Violation Component

---

src/app/fyle/team-advance/team-adv-card/team-adv-card.component.spec.ts

ClickUp:  https://app.clickup.com/t/85zru6cwy

test: Code Coverage 100% team advance card component

---

src/app/shared/components/fy-input-popover/fy-input-popover.component.spec.ts

test: Code Coverage: Fy-Input Popover Component

---

src/app/shared/components/footer/footer.component.spec.ts

clickUp: https://app.clickup.com/t/85zru69dy

test: Code Coverage 100% Footer component

---

src/app/shared/components/send-email/send-email.component.spec.ts

click up - https://app.clickup.com/t/85zru6at9

test: Code coverage: Send email component

---

src/app/core/mock-data/individual-expense-policy-state.data.ts
src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.spec.ts

test: Code Coverage: Fy-Policy Violation Info Component

---

src/app/shared/components/review-footer/review-footer.component.spec.ts

clickUp: https://app.clickup.com/t/85zruh0mx

fix: Resolved import related error

---

src/app/fyle/my-advances/my-advances-card/my-advances-card.component.spec.ts

test: Code Coverage: My Advances Card Component

---

src/app/shared/components/fy-approver/fy-approver.component.spec.ts

test: Code Coverage: Fy-Approver Component

---

src/app/shared/components/spent-cards/card-detail/card-detail.component.spec.ts

test: Code Coverage: Card Detail Component

---

src/app/fyle/dashboard/stats/stats.component.html

Clickup Link - https://app.clickup.com/t/85zrum963
Before - 
After -

fix: Offline state appearing twice on Home Screen

---

src/app/fyle/my-advances/my-advances-card/my-advances-card.component.spec.ts

fix: Code Coverage: My Advances Card Component

---

src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
src/app/shared/components/dependent-fields/dependent-fields.component.ts

Clickup - https://app.clickup.com
Changes:
- I had missed updating mileage and per-diem with changes for the refactoring. Have added them
- While testing, found an issue in edit expense where changing the project was not clearing  the dependent field. Have fixed it

fix: Fix issue in edit expense and add refactoring changes to mileage/per-diem

---

src/app/shared/components/popup-alert/popup-alert.component.spec.ts

click up - https://app.clickup.com/t/85zrut37z

fix: Disabling a test which fails at times

---

src/app/core/test-data/status.service.spec.data.ts

https://app.clickup.com/t/85zrumq72

test: updated status service mock data for expense rule comment

---

src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.spec.ts

test: Code Coverage: Add Txn To Report Dialog Component

---

src/app/shared/components/fy-delete-dialog/fy-delete-dialog.component.spec.ts

test: Code Coverage: Fy-Delete Dialog Component

---

src/app/shared/components/fy-popover/fy-popover.component.spec.ts

click up - https://app.clickup.com/t/85zru6amu

test: Code coverage: FyPopover Component

---

src/app/shared/components/fy-popup/fy-popup.component.spec.ts

test: Code Coverage: Fy-Popup Component

---

src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.spec.ts

test: Code Coverage: Personal Cards Matched Expenses Page Component

---

src/app/shared/components/fy-filter-pills/fy-filter-pills.component.spec.ts

click up - https://app.clickup.com/t/85zrv3wh6

test: Code coverage: FyFilterPills Component

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/view-expense/view-expense.page.html

https://app.clickup.com/t/865buepqr

feat: Show card transaction description, if present, in add edit expense page

---

src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.spec.ts

clickup: https://app.clickup.com/t/85zrv6pvu

test: code coverage TaskCard Component  91%

---

src/app/fyle/my-reports/my-reports.module.ts
src/app/fyle/team-reports/team-reports.module.ts

fix: Code Coverage: Reports Card Component #2

---

src/app/fyle/team-reports/team-reports.page.html

fix: Reports Cards Component

---

src/app/fyle/personal-cards/date-range-modal/date-range-modal.component.spec.ts

clickUp: https://app.clickup.com/t/85zrum1n2

test: Code coverage dateRangeModal component

---

src/app/fyle/add-edit-expense/add-edit-expense.page.ts

Clickup - https://app.clickup.com/t/85zrutu71

feat: Optimizations in getEditExpenseObservable

---

src/app/fyle/add-edit-expense/add-edit-expense.page.ts

Clickup - https://app.clickup.com/t/85zruurv8

feat: Optimization in getCategoryOnEdit

---

src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.spec.ts

click up - https://app.clickup.com/t/862jjxrpd

fix: Fixing a test on master

---

src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.spec.ts

test: Code Coverage: Bank Account Card Component

---

src/app/fyle/my-profile/preference-setting/preference-setting.component.spec.ts

clickUp: https://app.clickup.com/t/85zrv3w5a

test: Code coverage PreferenceSetting Component

---

src/app/shared/components/delegated-acc-message/delegated-acc-message.component.spec.ts

test: Code Coverage: Delegated Account Message Component

---

src/app/core/mock-data/org-settings.data.ts
src/app/core/services/payment-modes.service.spec.ts
src/app/core/services/permissions.service.spec.ts
src/app/core/services/report.service.spec.ts
src/app/core/services/sidemenu.service.spec.ts
src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.spec.ts
src/app/post-verification/setup-account-preferences/setup-account-preferences.page.spec.ts

test: Code Coverage: Setup Account Preferences Page Component

---

src/app/fyle/my-profile/employee-details-card/employee-details-card.component.html
src/app/fyle/my-profile/employee-details-card/employee-details-card.component.spec.ts

test: Code Coverage: Employee Details Card Component

---

src/app/core/mock-data/sidemenu-item.data.ts
src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.spec.ts

clickUp: https://app.clickup.com/t/85zrv7603

test: Code coverage 100% SidemenuContent Component

---

src/app/core/mock-data/formatted-policy-violation.data.ts
src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts

Clickup Link - https://app.clickup.com/t/85zrv75ea

test: 100 Coverage on split-expense-policy-violation

---

src/app/core/services/dependent-fields.service.ts
src/app/core/services/expense-fields.service.ts
src/app/core/services/merge-expenses.service.ts
src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.html
src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.ts
src/app/fyle/merge-expense/merge-expense.page.html
src/app/fyle/merge-expense/merge-expense.page.ts

Clickup - https://app.clickup.com/t/85zrum3pt
UI Preview:
https://user-images.githubusercontent.com/39493102/231183927-30124569-f752-4967-9e92-2dd1ef5395ec.mov

feat: Add cost center dependent field changes to merge expense page

---

src/app/fyle/view-expense/view-expense.page.ts
src/app/fyle/view-mileage/view-mileage.page.html
src/app/fyle/view-mileage/view-mileage.page.ts
src/app/fyle/view-per-diem/view-per-diem.page.html
src/app/fyle/view-per-diem/view-per-diem.page.ts

Clickup: https://app.clickup.com/t/85zrum3pc

feat: Add CC dependent fields to view mileage/per-diem page

---

src/app/core/services/router-auth.service.spec.ts
src/app/core/services/router-auth.service.ts

https://app.clickup.com/t/85zrwhkqn

fix: Added fix for expense aggregation

---

src/app/shared/components/navigation-footer/navigation-footer.component.spec.ts

test: Code Coverage: Navigation Footer Component

---

src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.spec.ts

clickUp: https://app.clickup.com/t/85zrv76cc

test: code coverage ExpensePreview Component 

---

src/app/core/mock-data/mileage-location.data.ts
src/app/shared/components/route-visualizer/route-visualizer.component.spec.ts

test: Code Coverage: Route Visualizer Component

---

src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/shared/components/route-selector/route-selector.component.ts

fix: Route Selector Component

---

src/app/core/services/currency.service.spec.ts

A spec is failing on master every now and then, removing the matcher for now.

fix: Currency Service

---

src/app/core/services/tasks.service.spec.ts
src/app/core/services/tasks.service.ts
src/app/fyle/dashboard/stats/stats.component.html
src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.spec.ts
src/app/fyle/dashboard/tasks/tasks.component.ts
src/app/fyle/my-expenses/my-expenses.service.ts
src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
src/app/fyle/my-view-report/my-view-report.page.html
src/app/fyle/my-view-report/my-view-report.page.scss
src/app/fyle/view-team-report/view-team-report.page.scss
src/app/shared/components/summary-tile/summary-tile.component.scss
src/app/shared/pipes/expense-state.pipe.spec.ts
src/app/shared/pipes/expense-state.pipe.ts
src/app/shared/pipes/report-state.pipe.spec.ts
src/app/shared/pipes/report-state.pipe.ts
src/theme/colors.scss

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1BqEjxdqrmda9VFE85xIlsJZWw7JXKa6A%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=_xAfn1e)
ClickUp: https://app.clickup.com/t/85zrutfqm

feat: Renamed unreported to complete

---

src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.spec.ts

Clickup - https://app.clickup.com/t/85zrw6h11

test: 100% Coverage for ReceiptPreviewThumbnail

---

src/app/shared/components/fy-view-attachment/fy-view-attachment.component.spec.ts

Clickup - https://app.clickup.com/t/85zrw6ne4

test: 100% Coverage of FyViewAttachment component

---

src/app/core/services/tasks.service.spec.ts
src/app/core/services/tasks.service.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1zRe5w2Ye5VOQw2RyOPcebuE3E4PA0Xko%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=MFRgoae)
ClickUp: app.clickup.com

fix: Fixed Complete expenses task card header for consistency

---

src/app/shared/components/fy-view-report-info/fy-view-report-info.component.spec.ts

Clickup - https://app.clickup.com/t/85zrw6n6a

test: 100% Coverage for fyViewReportInfo component

---

src/app/shared/components/personal-card-transaction/personal-card-transaction.component.spec.ts

clickUp: https://app.clickup.com/t/85zrw6h5u

test: code coverage 100% PersonalCardTransaction Component

---

src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
src/app/shared/components/capture-receipt/capture-receipt.component.ts

test: Code Coverage: Capture Receipt Component #1

---

src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.ts

BR - https://app.clickup.com/t/85zrtre5x
UI Preview

feat: Add max size upload limit to 5MB

---

src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.spec.ts
src/app/shared/components/fy-currency/fy-currency.component.html
src/app/shared/components/fy-multiselect/fy-multiselect-modal/fy-multiselect-modal.component.html
src/app/shared/components/fy-multiselect/fy-multiselect-modal/fy-multiselect-modal.component.spec.ts

test: Code Coverage: Receipt Preview Component

---

src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/shared/components/fy-location/fy-location.component.spec.ts
src/app/shared/components/fy-location/fy-location.component.ts
src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.html
src/app/shared/components/route-selector/route-selector.component.html

Clickup - https://app.clickup.com/t/85zrxnadh
Coverage -

test: 97% coverage for fy-location component

---

src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.spec.ts

Fixing Unit Tests

---

src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/shared/components/fy-multiselect/fy-multiselect.component.ts

fix: Fy-MultiSelect Component

---

.github/workflows/lint.yml
.github/workflows/unit-tests.yml

Clickup - https://app.clickup.com/t/85zryyg9a
Unit tests and eslint github actions are triggered only on PRs against master branch. I've changed the actions to trigger for all open PRs

feat: Trigger unit tests and eslint action for every PR

---

src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/shared/components/fy-userlist/fy-userlist.component.spec.ts
src/app/shared/components/fy-userlist/fy-userlist.component.ts

clickUp: https://app.clickup.com/t/85zrytq4t

test: Code coverage Fy-userlist component

---

src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.html
src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.spec.ts

test: Code Coverage: Approver Dialog Component

---

src/app/core/services/tasks.service.spec.ts
src/app/core/services/tasks.service.ts
src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.scss

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19OqbyVY1kuQR5BT8M2N2V9pKYy8YWDeKk%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=ovffttK)
ClickUp: https://app.clickup.com/t/85zrymt4f

fix: Improved complete expenses task header

---

src/app/core/mock-data/employee.data.ts
src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.spec.ts

clickUp: https://app.clickup.com/t/85zrxnand

test: Code Coverage Fy-userlist-modal component

---

src/app/core/services/categories.service.ts

Clickup : https://app.clickup.com/t/85zryw6jq

fix: Return category name only if it is enabled

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/shared/components/fy-select-vendor/fy-select-vendor.component.ts

fix: Fy-Select Vendor Component

---

src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.spec.ts
src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts

Clickup - https://app.clickup.com/t/85zrxnadz

test: 98% Coverage of fy-location-modal

---

src/app/fyle/add-edit-expense/add-edit-expense.page.html

Clickup -> https://app.clickup.com/t/85zrzvueq

fix: Pass empty array when custom properties is null in txn object

---

src/app/shared/components/fy-select-vendor/fy-select-modal/fy-select-vendor-modal.component.html
src/app/shared/components/fy-select-vendor/fy-select-modal/fy-select-vendor-modal.component.spec.ts

test: Code Coverage: Fy-Select-Vendor-Modal Component

---

src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.spec.ts

fix: Remove f-describe

---

src/app/shared/components/fy-select/fy-select.component.spec.ts
src/app/shared/components/fy-select/fy-select.component.ts
src/app/shared/components/fy-select/fy-select.interface.ts

Clickup - https://app.clickup.com/t/85zrxnafb
Merging this branch into the `ngControl` changes branch, and will then merge all of them into master

test: 100% Coverage of fySelect component

---

src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.html

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1B9JzOSPwswWrF6w0YPbKRECrsfGQbMU%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=YsuMvDt)
ClickUp: https://app.clickup.com/1ds31o

fix: Fixed potential duplicates task spacing

---

src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/split-expense/split-expense.page.html
src/app/shared/components/fy-select-project/fy-select-project.component.html
src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
src/app/shared/components/fy-select-project/fy-select-project.component.ts

test: Code Coverage: Fy-Select-Project Component

---

src/app/fyle/team-advance/team-adv-card/team-adv-card.component.spec.ts

clickUp: https://app.clickup.com/t/85zt291j0

fix: Team Adv Card component -  added fix for incorrect date

---

src/app/fyle/view-team-report/view-team-report.page.spec.ts

https://app.clickup.com/t/85zt0554q
This is the PR for the first and second part.
Will raise another PR for 100% for the 3rd part including DOM tests as well

test: Code Coverage: View Team Report #1

---

android/variables.gradle

Clickup - https://app.clickup.com/t/85zt0ahv3

fix: janus vulnerability-changed minsdk version to 24

---

src/app/core/mock-data/individual-expense-policy-state.data.ts
src/app/fyle/view-expense/view-expense.page.html
src/app/fyle/view-expense/view-expense.page.spec.ts
src/app/fyle/view-expense/view-expense.page.ts

clickUp: https://app.clickup.com/t/85zt056v3

test: Code Coverage 50%  View Expense Page

---

android/app/src/main/AndroidManifest.xml

Clickup - https://app.clickup.com/t/85zt0aj09

fix: remove unused permissions

---

android/app/src/main/AndroidManifest.xml

Clickup - https://app.clickup.com/t/85zt0ahw9

fix: strandhogg vulnerability - launchMode and taskAffinity

---

src/app/auth/sign-in/sign-in.page.scss

fix: Sign In Page Google Button Loader

---

src/app/core/enums/report-page-segment.enum.ts
src/app/core/enums/segment.enum.ts
src/app/fyle/my-view-report/my-view-report.page.spec.ts
src/app/fyle/my-view-report/my-view-report.page.ts

test: Code Coverage: My-View Report Page

---

src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.spec.ts

test: Code Coverage: Add Expenses To Report Component

---

src/app/auth/verify/verify.enum.ts
src/app/auth/verify/verify.page.spec.ts
src/app/auth/verify/verify.page.ts

https://app.clickup.com/t/85zt04zzb

test: 100% Coverage of Verify Page

---

src/app/fyle/my-profile/employee-details-card/employee-details-card.component.html
src/app/fyle/my-profile/employee-details-card/employee-details-card.component.scss
src/app/fyle/my-profile/my-profile.page.spec.ts
src/app/fyle/my-profile/my-profile.page.ts
src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.spec.ts
src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.ts

Clickup - https://app.clickup.com/t/85zt5r6wt
UI Preview:
For smaller screen:
For larger screen:
Show toast message instead of success dialog for non us orgs:
https://github.com/fylein/fyle-mobile-app/assets/39493102/e6a93101-725c-4b07-a310-e7fa476346bf

feat: Fix comments on mobile app implementation

---

.eslintrc.json

https://app.clickup.com/t/85zt5xabj

feat: Added linting rules for type issues inside shared folder

---

src/app/fyle/view-mileage/view-mileage.page.html
src/app/fyle/view-mileage/view-mileage.page.scss
src/app/fyle/view-mileage/view-mileage.page.spec.ts
src/app/fyle/view-mileage/view-mileage.page.ts

clickUp: https://app.clickup.com/t/85zt05a2p
**Changes Done :**
- Added minor changes in the scss file so that the flag icon appears properly
> **Before**
**Flagged**
**Unflagged**
- Made changes in the `flagUnflagExpense()` method
- Created a separate method for getting dialogProps in `removeExpenseFromReport()`

test: code coverage 50% View Mileage Page

---

src/app/core/services/policy.service.ts

https://app.clickup.com/t/85zt699n5

fix: Added types in policy service

---

src/app/core/services/popup.service.ts

https://app.clickup.com/t/85zt699nc

fix: Added types in popup service

---

.github/pull_request_template.md

Clickup - https://app.clickup.com/t/85zt6e291

feat: Add PR template

---

src/app/core/services/mileage-rates.service.ts

https://app.clickup.com/t/85zt699jz

fix: Added types : Mileage rates services

---

src/app/core/services/mileage.service.ts

https://app.clickup.com/t/85zt699k7

fix: Added types : Mileage services

---

src/app/core/models/overlay-response.modal.ts
src/app/core/services/back-button.service.ts

fix: Back Button Service

---

src/app/core/mock-data/stats-response.data.ts
src/app/core/models/v2/stats-response.model.ts

fix: Stats Response Model

---

src/app/core/services/advance-request-policy.service.ts

fix: Advance Request Policy Service 

---

src/app/core/models/txn-custom-properties.model.ts
src/app/core/services/custom-fields.service.ts

Fixed Types for custom inputs service
https://app.clickup.com/t/85zt699dk

fix: Custom Inputs Service

---

src/app/auth/switch-org/switch-org.page.html
src/app/auth/switch-org/switch-org.page.spec.ts
src/app/auth/switch-org/switch-org.page.ts
src/app/core/mock-data/org.data.ts

1. Some lines for performance tracking remain to be covered and in `ionViewWillEnter` for `navigate_back` and `fromEvent`
2. Certain branches are not getting covered due to edge cases or possibly conditions that may not actually happen in proceed and handle pop up
3. Rest of the branches have been covered by tweaking the current tests

test: Code Coverage: Switch Org Component

---

src/app/core/services/org-settings.service.ts
src/app/fyle/fyle-routing.module.ts
src/app/fyle/view-team-report/view-team-report-v2-routing.module.ts
src/app/fyle/view-team-report/view-team-report-v2.module.ts

https://app.clickup.com/t/86ctz82q6

feat: Added page routing to view-team-report page based on backend feature flag

---

src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/add-edit-expense/add-edit-expense.page.ts

Added Restriction Based on org settings for `Expense report field` in Edit Expenses
https://app.clickup.com/t/86cuqkdqd

feat: Added Add to report restriction in add edit report section

---

src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.ts

Added Split expenses restrictions in add edit expense
https://app.clickup.com/t/86cup8d7v
https://www.loom.com/share/c2e5e4e3668d453d9a85e31dbe13dc23?sid=d70686d9-be6c-4074-bf58-fd17e11a4373

feat: Added Split expenses restrictions in add edit expense

---

src/app/fyle/my-create-report/my-create-report.page.spec.ts
src/app/fyle/my-create-report/my-create-report.page.ts
src/app/fyle/my-view-report/my-view-report.page.spec.ts
src/app/fyle/my-view-report/my-view-report.page.ts

Added Filtering for Pending transactions in Add expenses to report and create new report.
https://app.clickup.com/t/86cuqqvvp
https://www.loom.com/share/16a7281bae5b4ea49596cf11d459b740?sid=20483fa7-14a5-465f-bf89-eacc54d6602c

feat: Added filtering for pending txns in create/ add to report dialog

---

src/app/core/mock-data/org-settings.data.ts
src/app/core/models/org-settings.model.ts
src/app/core/services/org-settings.service.spec.ts
src/app/core/services/org-settings.service.ts
src/app/core/services/tasks.service.spec.ts
src/app/core/services/tasks.service.ts
src/app/core/test-data/org-settings.service.spec.data.ts

Added filtering of pending txns in tasks if pending restriction is enabled from org settings.
https://app.clickup.com/t/86cur9q7n

feat: Added filtering of pending txns in tasks if pending restriction is enabled from org settings.

---

src/app/core/services/tracking.service.ts
src/app/fyle/my-expenses-v2/my-expenses-v2.page.spec.ts
src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts

Added Tracker to see how many users have selected a transaction with a pending state.
https://app.clickup.com/t/86cuu7nac

feat: Added Trackers

---

src/app/core/models/generated-form-properties.model.ts
src/app/fyle/merge-expense/merge-expense.page.ts

Reverts fylein/fyle-mobile-app#2810
https://app.clickup.com/t/86cuuhz02

fix: revert - removed the ccc_group_id

---

src/app/core/services/platform/v1/shared/expenses.service.spec.ts

Fixed unit test for shared/expenses

test: unit test fix  for shared/expenses

---

src/app/core/interceptors/httpInterceptor.ts

Added X-Page-Url and X-Source-Identifier in headers.

feat: Added Addition headers

---

src/app/core/interceptors/httpInterceptor.ts

Removed Query parameters from x page url header

feat: removed query param from x-page-url

---

src/app/core/services/tracking.service.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.ts

Added Tracker for tracking user who tried to split expense when restriction is enabled.

feat: added tracker for split expenses

---

karma.conf.js
src/app/core/mock-data/stats-dimension-response.data.ts
src/app/core/models/platform/v1/stats-response.model.ts
src/app/core/services/advance-request.service.spec.ts
src/app/core/services/advance-request.service.ts
src/app/core/services/tasks.service.spec.ts
src/app/core/services/tasks.service.ts
src/app/core/test-data/tasks.service.spec.data.ts

Fixing the tests here: https://github.com/fylein/fyle-mobile-app/pull/2846

feat: Move Advance request stats call to platform

---

src/app/core/models/view-type.enum.ts
src/app/core/services/advance-request.service.spec.ts
src/app/core/services/advance-request.service.ts
src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.setup.spec.ts
src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts

feat: fix Advance request edit in team advances

---

src/app/shared/components/fy-select-project/fy-select-project.component.ts

```js
{
label: string;
value: ExtendedProject;
selected?: boolean;
}
```
is used at multiple places, create an interface and import here.
[Please add link here](https://app.clickup.com/t/86cv9m9kb)

fix: Typescript Types | Fix failing test cases

---

src/app/core/mock-data/platform-report.data.ts
src/app/core/services/platform/v1/approver/reports.service.spec.ts
src/app/core/services/platform/v1/spender/reports.service.spec.ts
src/app/core/services/platform/v1/spender/reports.service.ts

fix: fix platform spender reports test coverage

---

src/app/core/services/projects.service.spec.ts

[Please add link here](https://app.clickup.com/t/86cvcgnky)

fix: Improved test cases ProjectsService

---

src/app/core/mock-data/platform-report.data.ts
src/app/core/services/platform/v1/spender/reports.service.spec.ts
src/app/core/services/report.service.spec.ts
src/app/fyle/my-create-report/my-create-report.page.spec.ts
src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts

fix: Fix create report PR tests [6]

---

src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts

feat: fix eslint issues

---

src/app/core/mock-data/platform-report.data.ts
src/app/fyle/my-view-report/my-view-report.page.html
src/app/fyle/my-view-report/my-view-report.page.spec.ts
src/app/fyle/my-view-report/my-view-report.page.ts
src/app/fyle/view-team-report/view-team-report.page.html
src/app/fyle/view-team-report/view-team-report.page.spec.ts
src/app/fyle/view-team-report/view-team-report.page.ts
src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts

PR contents:
- Moves report approvals to platform
Some tests failing in this PR, will add those in follow up.

feat: replace approvals call with call from platform

---

src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
src/app/fyle/my-expenses/my-expenses.page.spec.ts
src/app/fyle/my-expenses/my-expenses.page.ts
src/app/fyle/my-reports/my-reports.page.spec.ts
src/app/fyle/team-reports/team-reports-1.page.spec.ts
src/app/fyle/team-reports/team-reports.page.ts

test: Add test for simple search

---

src/app/fyle/my-view-report/my-view-report.page.html
src/app/fyle/team-reports/team-reports.page.html

fix: fix date keys in template

---

src/app/core/mock-data/platform-report.data.ts
src/app/core/test-data/status.service.spec.data.ts
src/app/fyle/my-view-report/my-view-report.page.html
src/app/fyle/my-view-report/my-view-report.page.ts
src/app/fyle/view-team-report/view-team-report.page.spec.ts
src/app/fyle/view-team-report/view-team-report.page.ts

fix: fix comment ordering and add support for edge case

---

src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.ts

updating the expense observable on adding or removing receipt
https://app.clickup.com/t/86cvhh5je

fix: updating the expense observable on adding or removing receipt

---

src/app/deep-link-redirection/deep-link-redirection.page.spec.ts
src/app/deep-link-redirection/deep-link-redirection.page.ts

fix: Deep link redirection fix

---

src/app/core/services/transaction.service.ts
src/app/fyle/my-expenses/my-expenses.page.ts

fixed the additional api calls happening on my expense page
https://app.clickup.com/t/86cvhh63c

fix: fixed the additional api calls happening on my expense page

---

src/app/core/mock-data/corporate-card-transaction-response.data.ts
src/app/core/mock-data/matchedCCTransaction.data.ts
src/app/core/models/platform/v1/corporate-card.model.ts
src/app/core/services/corporate-credit-card-expense.service.spec.ts
src/app/core/services/corporate-credit-card-expense.service.ts
src/app/core/services/transaction.service.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.html
src/app/fyle/view-expense/view-expense.page.html
src/app/shared/components/card-number/card-number.component.html
src/app/shared/components/card-number/card-number.component.scss
src/app/shared/components/card-number/card-number.component.ts
src/app/shared/components/corporate-card/corporate-card.component.html
src/app/shared/components/corporate-card/corporate-card.component.scss

Changing edit expense form by adding card nickname optionally & card design on dashboard by adding bank name and moving card logo to bottom right. Nickname is added optionally here as well.
https://app.clickup.com/t/86cvp13h0
1. Without nickname
2. With nickname
3. Edit expense form with nickname

feat: Changing edit expense form & card design on dashboard

---

src/app/fyle/my-view-report/my-view-report.page.html
src/app/fyle/view-team-report/view-team-report.page.html

feat: Change terminology for resubmit date

---

src/app/core/services/projects.service.ts

fix: fix empty search string returning no projects

---

src/app/core/models/my-reports-filters.model.ts
src/app/core/services/platform/v1/spender/reports.service.spec.ts
src/app/core/services/platform/v1/spender/reports.service.ts
src/app/core/services/report.service.spec.ts
src/app/core/services/report.service.ts
src/app/fyle/my-reports/my-reports.page.html
src/app/fyle/my-reports/my-reports.page.spec.ts
src/app/fyle/my-reports/my-reports.page.ts
src/app/fyle/my-view-report/my-view-report.page.spec.ts
src/app/fyle/my-view-report/my-view-report.page.ts
src/app/fyle/view-team-report/view-team-report.page.spec.ts
src/app/fyle/view-team-report/view-team-report.page.ts
src/app/shared/components/reports-card/reports-card.component.spec.ts
src/app/shared/components/reports-card/reports-card.component.ts

feat: Add delete report API to mobile app

---

src/app/fyle/my-view-report/my-view-report.page.html
src/app/fyle/view-team-report/view-team-report.page.html

fix: truncate long report names

---

src/app/core/services/report.service.spec.ts
src/app/core/services/report.service.ts
src/app/deep-link-redirection/deep-link-redirection.page.spec.ts
src/app/deep-link-redirection/deep-link-redirection.page.ts
src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
src/app/fyle/my-create-report/my-create-report.page.spec.ts
src/app/fyle/my-create-report/my-create-report.page.ts
src/app/fyle/my-expenses/my-expenses.page.spec.ts
src/app/fyle/my-expenses/my-expenses.page.ts
src/app/fyle/my-reports/my-reports.page.spec.ts
src/app/fyle/my-view-report/my-view-report.page.html
src/app/fyle/my-view-report/my-view-report.page.spec.ts
src/app/fyle/split-expense/split-expense.page.spec.ts
src/app/fyle/split-expense/split-expense.page.ts
src/app/fyle/team-reports/team-reports-1.page.spec.ts
src/app/fyle/team-reports/team-reports-2.page.spec.ts
src/app/fyle/team-reports/team-reports-3.page.spec.ts
src/app/fyle/team-reports/team-reports-4.page.spec.ts
src/app/fyle/team-reports/team-reports.page.setup.spec.ts
src/app/fyle/team-reports/team-reports.page.ts
src/app/fyle/view-team-report/view-team-report.page.html
src/app/fyle/view-team-report/view-team-report.page.spec.ts
src/app/fyle/view-team-report/view-team-report.page.ts
src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts
src/app/shared/components/create-new-report-v2/create-new-report.component.ts
src/app/shared/components/fy-add-to-report/fy-add-to-report.component.spec.ts
src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts

feat: remove unused service refs for Report Service

---

src/app/core/services/expense-fields.service.ts

https://app.clickup.com/t/86cw26bfg

fix: ordering expense fields based on seq so that the filtering config based on category is correct everytime

---

src/app/fyle/dashboard/tasks/tasks.component.ts
src/app/fyle/my-advances/my-advances.page.ts
src/app/fyle/my-expenses/my-expenses.page.ts
src/app/fyle/team-advance/team-advance.page.ts
src/app/fyle/team-reports/team-reports.page.ts

Typeerror - Complete is not a function(.complete is undefined)
I have implemented optional chaining on the complete method also so that
It will check complete method exist on target or not and if not it will evaluate to undefined without throwing an error
Like this: event?.target?.complete?.();

fix: complete method undefined typeerror

---

src/app/core/services/tracking.service.ts

https://app.clickup.com/t/86cw2ydpr

fix: for same user counted as multiple users on mixpanel

---

src/app/shared/components/expenses-card-v2/expenses-card.component.html
src/app/shared/components/expenses-card-v2/expenses-card.component.scss

https://app.clickup.com/t/86cw6cawt

feat: Dupicate icon in expense card

---

src/app/core/services/org-settings.service.ts
src/app/core/services/projects.service.spec.ts
src/app/core/services/projects.service.ts
src/app/core/services/recently-used-items.service.spec.ts
src/app/core/services/recently-used-items.service.ts
src/app/core/test-data/org-settings.service.spec.data.ts
src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
src/app/shared/components/fy-select-project/fy-select-project.component.ts

https://app.clickup.com/t/86cwaan7v

fix: mileage and per diem forms to show all projects if project-category restriction is diabled

---

src/app/core/mock-data/org-settings.data.ts
src/app/core/services/org-settings.service.ts
src/app/core/services/projects.service.spec.ts
src/app/core/services/projects.service.ts
src/app/core/services/recently-used-items.service.spec.ts
src/app/core/services/recently-used-items.service.ts
src/app/core/test-data/org-settings.service.spec.data.ts
src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
src/app/fyle/split-expense/split-expense.page.spec.ts
src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
src/app/shared/components/fy-select-project/fy-select-project.component.ts

https://app.clickup.com/t/86cw9qjtg

test: fixing test coverage for project category restriction checks

---

src/app/core/mock-data/org-settings.data.ts
src/app/core/services/org-settings.service.ts
src/app/core/services/projects.service.spec.ts
src/app/core/services/projects.service.ts
src/app/core/services/recently-used-items.service.spec.ts
src/app/core/services/recently-used-items.service.ts
src/app/core/test-data/org-settings.service.spec.data.ts
src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.ts
src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
src/app/fyle/split-expense/split-expense.page.spec.ts
src/app/fyle/split-expense/split-expense.page.ts
src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
src/app/shared/components/fy-select-project/fy-select-project.component.ts

https://app.clickup.com/t/86cw215hr

feat: adding project category restriction checks while setting split expense values based on project - part 2

---

src/app/core/mock-data/expense-filters.data.ts
src/app/core/mock-data/filter-options.data.ts
src/app/core/mock-data/filter-pills.data.ts
src/app/core/mock-data/selected-filters.data.ts
src/app/core/services/platform/v1/shared/expenses.service.spec.ts
src/app/fyle/my-expenses/my-expenses.page.spec.ts
src/app/fyle/my-expenses/my-expenses.service.spec.ts

https://app.clickup.com/t/86cw7ngz0

test: fixed test cases of potential duplicates filter

---

src/app/core/models/platform/v1/expense.model.ts

https://app.clickup.com/t/86cw6cawt

fix: Added is_duplicate present key in expense modal

---

src/app/core/services/tracking.service.ts

https://app.clickup.com/t/86cw5ddyq

fix: set mixpanel track_pageview to false

---

src/app/fyle/notifications/notifications.page.ts

fix: delegatee notification display issue

---

src/app/fyle/notifications/notifications.page.ts

fix: fix for delegatee notification visibility

---

src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts

https://app.clickup.com/t/86cwbmr1n

fix: assiging isProjectCategoryRestrictionsEnabled before using it

---

src/app/fyle/my-expenses/my-expenses.page.ts

https://app.clickup.com/t/FYLE-86cw6cawt

fix: potential duplicate filter pill click

---

src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
src/app/fyle/add-edit-expense/add-edit-expense.page.ts

https://app.clickup.com/1864988/v/l/6-901603627242-1

fix: Fyle project category r fix

---

hooks/utils/prod-environment.js
src/app/core/services/router-auth.service.spec.ts
src/app/core/services/router-auth.service.ts
src/app/core/services/tracking.service.ts
src/environments/environment.ts

https://app.clickup.com/t/86cw2ydpr

feat: add and use ENABLE_MIXPANEL and USE_MIXPANEL_PROXY env variable

---

src/app/core/interceptors/httpInterceptor.spec.ts

Modifications in the httpInterceptor.spec.ts file to increase the code coverage , written some unit tests to cover all statements

Fix: http interceptor behaviouralbug test

---

src/app/fyle/merge-expense/merge-expense.page.ts

fix: merge expenses data of expenses is undefined

---

src/app/core/services/split-expense.service.spec.ts
src/app/core/services/transaction.service.spec.ts
src/app/core/services/transaction.service.ts
src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts

chore: cleanup unused methods

---

src/app/fyle/add-edit-expense/add-edit-expense.page.ts

https://app.clickup.com/t/86cwh4tzb

fix: Replace the scanning receipt loader for single mode

---

src/app/core/interceptors/httpInterceptor.spec.ts
src/app/core/interceptors/httpInterceptor.ts
src/app/fyle/personal-cards/personal-cards.page.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1iO9BoR0jBdaMWFnHDH2dHZpFEt2Bnf8%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=yZUvgeg)

fix: Reverted interceptor changes

---

src/app/core/services/transactions-outbox.service.ts
src/app/shared/components/capture-receipt/capture-receipt.component.ts
src/app/shared/components/expenses-card-v2/expenses-card.component.ts
src/app/shared/components/expenses-card/expenses-card.component.ts

https://app.clickup.com/t/86cwgw534

Remove DE related logic from TransactionOutboxService and expenses card component

---

README.md
src/app/core/models/image.model.ts
src/app/core/services/platform/v1/spender/expenses.service.ts
src/app/core/services/transaction.service.spec.ts
src/app/core/services/transaction.service.ts
src/app/core/services/transactions-outbox.service.ts
src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
src/app/shared/components/capture-receipt/capture-receipt.component.ts
src/app/shared/components/expenses-card-v2/expenses-card.component.ts
src/app/shared/components/expenses-card/expenses-card.component.ts

https://app.clickup.com/t/86cwgw5af

feat: TransactionService changes for expenses POST to platform

---

README.md
src/app/core/services/platform/v1/spender/expenses.service.spec.ts
src/app/core/services/platform/v1/spender/expenses.service.ts
src/app/core/services/transaction.service.spec.ts
src/app/core/services/transaction.service.ts
src/app/core/services/transactions-outbox.service.ts
src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
src/app/shared/components/capture-receipt/capture-receipt.component.ts
src/app/shared/components/expenses-card-v2/expenses-card.component.ts
src/app/shared/components/expenses-card/expenses-card.component.ts

https://app.clickup.com/t/86cwgw4yw

feat: ExpensesService.createFromFile()

---

README.md
src/app/core/mock-data/transaction.data.ts
src/app/core/services/platform/v1/spender/expenses.service.spec.ts
src/app/core/services/platform/v1/spender/expenses.service.ts
src/app/core/services/transaction.service.spec.ts
src/app/core/services/transaction.service.ts
src/app/core/services/transactions-outbox.service.ts
src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
src/app/shared/components/capture-receipt/capture-receipt.component.ts
src/app/shared/components/expenses-card-v2/expenses-card.component.ts
src/app/shared/components/expenses-card/expenses-card.component.ts

https://app.clickup.com/t/86cwgw4ug

feat: ExpensesService.transformTo method for moving expenses POST to platform

---

.github/CODEOWNERS

feat: adding Arjun as code owner

---

src/app/core/services/transactions-outbox.service.spec.ts
src/app/fyle/my-expenses/my-expenses.page.spec.ts
src/app/fyle/my-expenses/my-expenses.page.ts
src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
src/app/shared/components/expenses-card/expenses-card.component.spec.ts

https://app.clickup.com/t/86cwhjew2

fix: remove dead test code, fix failing tests

---

src/app/fyle/dashboard/tasks/tasks.component.ts
src/app/fyle/my-expenses/my-expenses.page.spec.ts
src/app/fyle/my-expenses/my-expenses.page.ts

reword transction to expense

---

src/app/fyle/personal-cards/personal-cards.page.html

https://app.clickup.com/t/86cwm1x6j

fix: minor comment

---

src/app/core/interceptors/httpInterceptor.ts

fix: throwing 401 singin related errors back from interceptor

---

src/app/fyle/my-expenses/my-expenses.page.html
src/app/fyle/my-expenses/my-expenses.page.scss

[clickup link](https://app.clickup.com/t/86cx9vxqy)
https://github.com/user-attachments/assets/64433d94-85be-477e-809c-e89335bc4976

fix: Update smaller screen size design for header

---

src/app/fyle/view-expense/view-expense.page.html
src/app/fyle/view-expense/view-expense.page.scss
src/app/fyle/view-mileage/view-mileage.page.html
src/app/fyle/view-mileage/view-mileage.page.scss
src/app/fyle/view-per-diem/view-per-diem.page.html
src/app/fyle/view-per-diem/view-per-diem.page.scss
src/app/fyle/view-team-report/view-team-report.page.html
src/app/fyle/view-team-report/view-team-report.page.scss
src/app/fyle/view-team-report/view-team-report.page.spec.ts
src/app/fyle/view-team-report/view-team-report.page.ts
src/app/shared/components/fy-alert-info/fy-alert-info.component.scss
src/app/shared/components/popup-alert/popup-alert.component.html
src/app/shared/components/popup-alert/popup-alert.component.scss
src/app/shared/components/popup-alert/popup-alert.component.ts
src/app/shared/shared.module.ts

> [!IMPORTANT]  
> This PR contains all the approved child PRs ✅
[Please add link here](https://app.clickup.com/t/86cx5a7d6)

feat: Milestone 3: Team-Reports view display exact amount

---

package-lock.json

fix: Fix vuln issues using npm audit fix

---

src/app/core/services/dependent-fields.service.spec.ts
src/app/core/services/dependent-fields.service.ts
src/app/core/test-data/dependent-fields.service.spec.data.ts

https://app.clickup.com/t/86cxu0uze

fix: adding limit of 200 while fetching dependent field values
