fylein/fyle-mobile-app

- src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> Fixed typo in cancel dialog on add mileage expense page

- src/app/shared/components/fy-userlist/fy-userlist.component.ts
issue: 
- value was not getting updated in fields on the expense page while selecting new or removal of users
fix:
- sending cloned variable so the reference value will not get updated and this will solve the problem
> fixed user list custom field custom component

- src/app/fyle/add-edit-expense/add-edit-expense.page.html
- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
- src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
- src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
- src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
- src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Case:
- enable_individual_projects setting is true
- no projects set for the employee
- project is not mandatory
The message shows `There are no projects assigned to you, the expense will go to draft`
This should be shown only if the project is mandatory
> proj-message-fix: Hiding the warning message if project is not mandatory

- src/app/app-routing.module.ts
Before it shows login screen -> org Switcher - > dashboard
Now logged-in users directly lands on dashboard
> Showing dashboard on app startup for logged-in users

- src/app/fyle/add-edit-expense/add-edit-expense.page.html
- src/app/fyle/add-edit-expense/add-edit-expense.page.scss
- src/app/fyle/split-expense/split-expense.page.ts
**Issue:**
- The transaction object is set using - `this.transaction = JSON.parse(this.activatedRoute.snapshot.params.txn);` 
- This has the date formats in the form of a string, due to which, if there are mandatory category dependent date fields such from date / to date, the system throws an error blocking split expense
**Fix:**
- To fix this, explicitly converting the date while saving the split expense
- Affected user on hulk - `usb6ejcefime@fyleinbrodart.com` / anyone from Brodart using `Travel / Hotel & Tax` category
**Other fixes:**
- Restricting users to split an already reported expense
- Restricting users to split in offline mode
- Minor spacing fix added for split expense button in the expense form
> FYLE-6f6u77: Fix for split expense issue with from and to date

- src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
- src/app/fyle/add-edit-expense/fy-currency/fy-currency.component.scss
Align currency and amount in add expenses:
Before:
After without invalid input error
After with invalid input error
Make boolean non-mandatory in advances page:
Before:
https://user-images.githubusercontent.com/39493102/131671751-34bfda02-8fc2-4827-95a5-da572317d9d8.mp4
After:
https://user-images.githubusercontent.com/39493102/131671764-e67f315e-8d30-452c-bf20-d4c97d144b41.mp4
> Align currency and amount in add expense and make boolean non-mandatory in advances page

- src/app/fyle/add-edit-expense/add-edit-expense.page.html
- src/app/fyle/add-edit-expense/add-edit-expense.page.scss
- src/app/fyle/capture-receipt/add-more-popup/add-more-popup.component.scss
- src/app/fyle/team-reports/team-reports.page.scss
Info alert box top padding in offline mode
Before:
After:
Team reports add padding to last report
Before:
After:
Gallery icon color in receipt preview:
Before:
After:
> Fix minor bugs

- src/app/fyle/personal-cards/personal-cards.page.scss
- src/app/shared/components/bank-account-cards/bank-account-cards.component.scss
> Fix for black bg in personal cards on iOS

- src/app/fyle/my-profile/my-profile.page.html
- src/app/fyle/my-profile/my-profile.page.scss
- src/theme/colors.scss
Issue: The background color was not applied on the entire page so it defaults to white when content is small.
Before: 
After:
> Remove duplicate color and fix background in profile page

- src/app/fyle/capture-receipt/crop-receipt/crop-receipt.component.html
This solves the `Incorrect Padding` and `CORS error` issues
> Save cropped image as jpeg

- src/app/fyle/add-edit-expense/add-edit-expense.page.html
- src/app/fyle/add-edit-expense/add-edit-expense.page.scss
- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
- src/theme/colors.scss
- Making `Add to report` mandatory during add expense
- Adding a different background to the `Add to report` section in the expense form
- On Save and new, redirect to expense form with report name filled
> FYLE-1z55me7: Prompt report submission mobile app changes

- src/app/app.component.ts
The error is because we are switching the swipe gesture while the menu controller is closing(animating). So adding a timeout of 500ms so that the swipe gesture is enabled/disabled after the animation
Ps - This also fixes the annoying debuggers we see on the browser while switching routes
Ref - https://github.com/ionic-team/ionic-framework/issues/19000
> Fix `Assert: cannot be animating` error in mobile app

- android/app/src/main/res/xml/config.xml
- ios/App/App/config.xml
It doesn't matter what value is added to origin - https://capacitorjs.com/docs/v2/cordova/using-cordova-plugins#:~:text=Capacitor%20does%20not%20support%20Cordova%20install%20variables%2C%20auto%20configuration%2C%20or%20hooks%2C%20due%20to%20our%20philosophy%20of%20letting%20you%20control%20your%20native%20project%20source%20code%20(meaning%20things%20like%20hooks%20are%20unnecessary).
VAPT DOC - https://www.notion.so/fyleuniverse/Vapt-q1-2022-fa65f76bc48f48f68e2974c07f7738da#40f7e5abb7404dd8aced6dadd7e13f43
> Fix Whitelisted URLs issue in both ios and android

- android/app/src/main/AndroidManifest.xml
🟢 Tested the changes on android
Notion link - https://www.notion.so/fyleuniverse/Vapt-q1-2022-fa65f76bc48f48f68e2974c07f7738da#51f394d497314f4e84cca2d27f329570
The other permissions are added by google play services which we use for showing push notifications - https://stackoverflow.com/questions/32646830/more-permissions-in-uploaded-apk-than-in-manifest-file
> Remove audio permissions in android app

- android/app/build.gradle
- android/app/proguard-rules.pro
- android/app/src/main/AndroidManifest.xml
Issue - Application backup might contain sensitive information private data of the app into their PC
Docs - https://developer.android.com/guide/topics/manifest/application-element#:~:text=for%20more%20information.-,android%3AallowBackup,via%20adb.%20The%20default%20value%20of%20this%20attribute%20is%20true.,-Note%3A%20If%20your
Issue - Application is vulnerable to reverse engineering without any obfuscation
Docs - https://developer.android.com/studio/build/shrink-code#groovy
> Disable backup and obfuscate bytecode

- src/app/shared/components/expenses-card/expenses-card.component.scss
8px spacing between merchant and project
> 8px spacing between merchant and project

- src/app/fyle/add-edit-expense/add-edit-expense.page.html
- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
- src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
- src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
- src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
- src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Slack thread - https://fylein.slack.com/archives/CFGRGRY2X/p1649840010266779
The issue:
- When clicking on `Potential Duplicates` task and selecting expense, we saw an option to delete the expense even if it was already a part of report. 
- While redirecting to expense from `View Report`, we pass a `remove_from_report` query param which was not passed here and so we were trying to delete expense from report instead of removing it which is an illegal action.
Solution:
- Hide the delete icon when redirection from duplicate task like we do in the web app
Approach:
- We show the delete icon in two cases - when the report has more than one expense and we can remove it from the report or when we want to delete an unreported expense
- I have added two new member vars - `isRedirectedFromReport` …
> Fix logic for deleting expenses

- src/app/core/services/tracking.service.ts
Sample values for my device
```
manufacturer:"OnePlus"
model:"AC2001"
operatingSystem:"android"
OVersion:"11"
platform:"android"
webViewVersion:"102.0.5005.125"
```
We can get the actual device name from the manufacturer + model details
Added the os, platform and webview version details just for additional debugging
I've also added app version to all mixpanel events, so we dont need to refer the db everytime
> Add device info in mixpanel events

- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
- src/app/fyle/dashboard/stats/stats.component.ts
- src/app/shared/components/sidemenu/sidemenu.component.ts
https://sentry.io/organizations/fyle-technologies-private-limi/issues/3300138618/?project=5622998&referrer=slack
- Fixed all such occurrences where `corporate_credit_card_settings` wasn't checked to be present before reading
> Fixed - Cannot read properties of null (reading 'corporate_credit_card_settings')

- src/app/post-verification/invited-user/invited-user.page.ts
Sentry link - https://sentry.io/organizations/fyle-technologies-private-limi/issues/3065970118/?project=5622998&query=is%3Aunresolved
Could not repro but this should fix the error
> Fix sentry error - Cannot read properties of null (reading 'us')

- src/app/fyle/add-edit-expense/add-edit-expense.page.html
- src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
- src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
The add to report change went out in the last live update release
There was a case missed when `canRemoveFromReport` was false while creating expenses, this has been fixed
> Fix for Add to report not appearing while creating expense

- src/app/core/services/transactions-outbox.service.ts
- src/app/shared/components/expenses-card/expenses-card.component.scss
- Fixes the issue where duplicate expenses were created if the receipt upload errors out
- Also fixed the image shrink issue when the expense is still in outbox
> Fix duplicates in bulk fyle and shrinking image thumbnail

- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
- src/app/shared/components/capture-receipt/capture-receipt.component.scss
- Previously, on clicking the `:` button, we showed the mandatory fields to be entered
- In the case of the Web app, we don't require to fill mandatory fields for Unlinking card details or dismiss/marking them as personal
- To fix this inconsistency in the mobile app, after this change:
- On clicking the dot menu, we show the options available to the user
- If the user wants to split an expense, they will have to fill the mandatory fields
- Users will no longer have to fill mandatory fields to unlink card details or dismiss/mark as personal
https://user-images.githubusercontent.com/31147415/179176001-3d1941b3-5030-41f1-abc3-3ecf78e9dad5.mov
> FYLE-2gg3hqk: Removed inconsistency in mobile app while unlinking card from an expense

- src/app/fyle/view-expense/view-expense.page.html
- src/app/fyle/view-mileage/view-mileage.page.html
- src/app/fyle/view-per-diem/view-per-diem.page.html
Issue: In mobile app, we show cost center id which we assign internally, instead of cost center code which the admin assigns   to the cost center. This will make the behaviour consistent in web and mobile app
BR link: https://app.clickup.com/t/2me4u8a
> Show Cost center code instead of id in view expense/mileage/perdiem

- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Issue: In mobile app, when user changes the category, we just hide category dependent fields and do not clear them from the etxn object and because of this policy is not working on some expenses due to criteria mismatch.
BR link: https://app.clickup.com/t/2jukcc4
> Clear all category dependent fields when user changes the category

- src/app/fyle/camera-overlay/camera-overlay.page.html
- src/app/fyle/camera-overlay/camera-overlay.page.ts
- src/app/shared/components/capture-receipt/capture-receipt.component.ts
- BR link - https://app.clickup.com/t/2np4ufy
- The issue is because, `ngAfterViewInit()` is not getting called sometimes when we use instafyle, save the expense and open the camera again. 
- I've replaced angular llifecycle hooks with the ones provided by ionic - `ionViewWillEnter()` and `ionViewWillLeave()`. This is what ionic recommends as well - [Ref](https://ionicframework.com/docs/angular/lifecycle#:~:text=When%20an%20app,a%20page%20%22popped%22.)
> Fix ios camera preview preview not working sometimes

- src/app/core/services/status.service.ts
- src/app/shared/components/comments-history/audit-history/audit-history.component.ts
**undefined is not an object (evaluating 'this.estatuses.map')** → https://sentry.io/organizations/fyle-technologies-private-limi/issues/3490627822/?referrer=slack
> Fail safe for estatuses sentry error

- src/app/core/services/launch-darkly.service.ts
- src/app/shared/components/fy-number/fy-number.component.html
- src/app/shared/components/fy-number/fy-number.component.ts
- BR link - https://app.clickup.com/t/2fkq1y2
- Tested these changes on iphone 13 🟢  for both cases locally
- This will allow all users in regions with period as decimal separator(includes USD) to use third party keyboards, but users in other regions will still have to use ios default keyboard
- Will add a flag in LD after this pr is approved
> Add ld flag to disable keyboard plugin

- src/app/core/services/offline.service.ts
- src/app/shared/components/expenses-card/expenses-card.component.html
- src/app/shared/components/expenses-card/expenses-card.component.ts
> Removal of expense fields from loadOptimise() method of offline service

- src/app/core/models/org_user_settings.model.ts
- src/app/core/services/offline.service.ts
- src/app/core/services/payment-modes.service.spec.ts
- src/app/core/services/payment-modes.service.ts
- src/app/core/services/view-expense.service.ts
- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
- src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
- src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
- src/app/fyle/view-expense/view-expense.page.ts
- src/app/fyle/view-mileage/view-mileage.page.ts
- src/app/fyle/view-per-diem/view-per-diem.page.ts
- src/app/shared/components/capture-receipt/capture-receipt.component.ts
Changes in this pr
- Check if payment_mode_settings is allowed and enabled and the LD flag is set before using the new flow
- Do not show PERSONAL_ACCOUNT payment mode in view mileage/per-diem if it is the only possible option. Since, we dont allow CCC in mileage/per-diem, this will happen only when ADVANNCE nad COMPANY both accounts are not present like when allowed_payment_modes is["PCCC"] or ["PCCC, PA"] or ["PA", "PCCC"]
> #payment_mode_configurations - Minor changes

- src/app/core/services/tasks.service.ts
- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
- src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
- src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
- src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
- src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
- src/app/fyle/dashboard/tasks/tasks.component.ts
- src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
Changes:
- Update the add to report modal in mileage/per-diem expenses if auto submission is scheduled
- Do not show auto-submission info card in teams section (We dont have team advances tasks so it'll be shown there)
- Hide unreported expenses and unsubmitted reports task if auto submission is scheduled
- Change report field name to `Expense Report` if auto submission is enabled
> #automate_report_submission: Changes in mileage/per-diem and other changes

- src/app/fyle/merge-expense/merge-expense.page.ts
Slack thread - https://fylein.slack.com/archives/CBYUKTQKZ/p1663157130080239?thread_ts=1663147088.659189&cid=CBYUKTQKZ
When merging two expenses, if the second or later expense is ccc, we pass `null` in `ccce_group_id` and so the transaction goes back to the `INITIALIZED` state from `IN_PROGRESS` state
> Fix ccc merge

- src/app/fyle/add-edit-expense/add-edit-expense.page.html
- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Changes:
- For incomplete expenses, title changes from`Edit Expense` to `Review Expense`
- Added an warning box to remind user to save the expense
> #mission_nps_mobile_40: Add info box and change title for INCOMPLETE expenses

- src/app/fyle/my-reports/my-reports.page.ts
The filter on Reports page on the mobile app did not have Payment Processing Filter, which has now been added
> Add Missing Filter : Payment Processing

- src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
- src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
- src/app/fyle/add-edit-expense/add-edit-expense.page.html
- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
- src/app/fyle/my-expenses/my-expenses.page.html
- src/app/fyle/my-expenses/my-expenses.page.ts
- src/app/shared/components/capture-receipt/capture-receipt.component.html
- src/app/shared/components/capture-receipt/capture-receipt.component.ts
Issue:
- We're getting errors like `camera already started` and `camera already stopped` very frequently
- Previously, we used to track camera preview using a flag called `isCameraShown`, but the problem here is that we used to set this flag only when the camera started or stopped, and not when we initiated the request to start/stop the camera
- The camera plugin takes some time to start/stop the camera preview, and hence we may get the above errors if the user tries to open the camera in between
- Also, we cannot change `isCameraShown` to track when the camera start/stop request was initiated, as we use it hide the parent components, and if we do so, the the user would see a weird UI till the camera preview actually starts
Solution
- Created a new flag `isCameraPreviewInitiated` to track …
> Add new var for tracking if camera preview has been initiated

- src/app/fyle/my-create-report/my-create-report.page.ts
When creating a new report the title of the report was not autopopulating
> Create Report Title Bug

- src/app/core/services/tasks.service.ts
The filter pill was displaying draft even after changing the filter label to incomplete
> Task Filter Pill Bug Fix

- src/app/fyle/dashboard/stats/stats.component.html
- src/app/fyle/dashboard/stats/stats.component.ts
- There were 2 variables used to get the cardTransactionsAndDetails
- One was the observable `cardTransactionsAndDetails$` and the other was the subscribed list value `cardTransactionsAndDetails`
- When the corporate card settings were enabled, cardTransactionsAndDetails$ and cardTransactionsAndDetails both got set
- In the else block, only the observable was set to null, the `cardTransactionsAndDetails` list was not set to an empty list
- Due to this, when we switched to an org with the settings disabled from an org that had card details, it showed up the previous data, basically, the list didn't get reset at all
- This also happened because we didn't call the initialize method if the settings were disabled, that's why the value never got reset
- I have added the change to reset the …
> FYLE-2uw0r29: Fix for cards of different org showing up on dashboard and clean up

- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
If the category field is dirty, dont change the category with user entered category
> #mission_nps_mobile_40:  Dont overwrite user-entered category with DE extracted category

- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Save expense prompt should be shown irrespective of extracted data
> #mission_nps_mobile_40: Fix condition for showing save expense prompt

- src/app/shared/components/capture-receipt/capture-receipt.component.ts
`Camera.requestPermissions()` is not implemented for web, so directly use `startCamera()` for web
> #mission_nps_mobile_40: Fix camera not working in browser

- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
- When the project got preset, the project watcher did not trigger, due to which the allowed categories filter method did not get called
- I have explicitly added checks to filter the allowed categories for recent categories as well as the all-category list
- As soon as the project is preset, we filter out the allowed categories
- We will autofill category only if it is allowed for that particular project
- Setting the form group project value explicitly before the patch which triggers the project watcher and filters out the allowed categories
> Fix for project<>category mapping issues

- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Fixes two issues. We switch back to autofill iff:
- DE extracted category is not enabled for the org - https://app.clickup.com/t/2x6fx89
- DE extracts `unspecified` category
> #mission_nps_mobile_40: Use autofill if DE extracts invalid category

- src/app/core/services/projects.service.ts
Fixes https://app.clickup.com/t/2y8wx9x
Issue:
- In mileage and per-diem forms, we filter the projects to show only the projects that are allowed for `Mileage` or `Per Diem`
- When comparing the project ids, in the `getProjectCount()` method in projects service, we were passing category ids as an array of string
- But, the API returns allowed category ids as an array of numbers. And so, the intersection always returned an empty array because of which the project field was not shown for mileage/per-diem expenses
Solution:
- Converted `string[]` to `number[]` inside the `getProjectCount()` method before checking for intersection
> Fix project field not visible in mileage/per-diem forms

- src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.html
- src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.ts
- src/app/shared/components/sidemenu/sidemenu.component.html
- src/app/shared/components/sidemenu/sidemenu.component.ts
Now clicking on the name of the user on top of the menu will take the user to the profile page.
https://user-images.githubusercontent.com/115472256/203004499-2bdb5cf1-eb2a-4d52-830d-992db2adb818.mov
Ripple effect added and click handler now relies on event emitter from sidemenu-header to parent component. 
https://user-images.githubusercontent.com/115472256/203482899-c757ec2f-be32-41a2-8e30-c22ad1518fb4.mov
Ripple effect improved and refactor
> Org And Name Area Clickable

- src/app/fyle/add-edit-expense/add-edit-expense.page.html
- src/app/fyle/add-edit-expense/add-edit-expense.page.scss
The info box position has been fixed, it now appears above the card information but the dot menu is not visible, hidden under spilt expense allowed condition
> Info Box In Review Expenses

- src/app/fyle/add-edit-expense/add-edit-expense.page.html
- src/app/fyle/add-edit-expense/add-edit-expense.page.scss
The info box position has been fixed, it now appears above the card information but the dot menu is not visible, hidden under spilt expense allowed condition
> Infobox update

- android/app/capacitor.build.gradle
- android/app/src/main/assets/capacitor.plugins.json
- android/app/src/main/res/xml/config.xml
- android/capacitor.settings.gradle
- ios/App/App/config.xml
- ios/App/Podfile
- package-lock.json
- package.json
- src/app/app.component.ts
- I'm using capacitor's official `text-zoom` plugin here - https://capacitorjs.com/docs/apis/text-zoom
- It has been around for a while and already has support for Capacitor 4
- Tested on both android and IOS 🟢 
- Will get a green from Sumanth and Bhavika before merging and we'll do a staged release as discussed
> #mission_nps_mobile_40: Use app font size irrespective of device native font size

- src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
Fixes: https://sentry.io/organizations/fyle-technologies-private-limi/issues/3283451811/?cursor=0%3A50%3A0&project=5622998&referrer=issue-stream
Call `CameraPreview.stop()` only if camera is in STARTING or RUNNING state
> Stop camera only if it is in starting or running state

- src/app/fyle/dashboard/dashboard.page.ts
- Sometimes all the expense types available for the org users are not shown when clicking on the plus icon in the dashboard
- This probably happens because the orgsetting call is present in `ngOnInit()`
- So, if the user is on dashboard of some org where mileage/per-diem are not enabled, and then he switches to a different org where these settings are enabled, the `actionSheetOptions` array will not be updated as the dashboard page is already in stack.
Slack thread - https://fylein.slack.com/archives/CFGRGRY2X/p1670516936272879
> Fix: Add Mileage/Per-diem option is sometimes not visible on dashboard

- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
- In cases where DE extracts `unspecified` as the category, and we use autofill, custom inputs are not shown.
- `customInputs$` emits a value when the category field is changed i.e. `fg.controls.category.valueChanges` emits a new value.
- Here, when we'e patching values for the entire form, we're setting `emitEvent` to `false` which does not trigger valueChanges
- Removiong the property for the entire form may lead to some other issues. So, I'm patching the value of category separately which triggers valueChanges event, and the custom fields are shown.
> #mission_nps_mobile_40: Fix custom inputs not shown when using instafyle

- src/app/core/services/transactions-outbox.service.ts
- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
- src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
- src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
- src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.ts
Fixes:
- If user opens add/edit expense from view report page, he'll be redirected to the same page after saving expense
- If add/edit expense is opened from dashboard or expenses page, he'll be redirected to expenses page irrespective if expense is added to a report or not.
> Fix expense/mileage/per-diem redirections

- src/app/shared/components/bank-account-cards/bank-account-cards.component.ts
Issue: In the url for fetching transactions, the card id is undefined. So the API throws 400. The event object that we’re listening to is an array while we’re expecting an object.
> Fix personal cards bug

- src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
- When we click on gallery icon, we stop the camera before opening the imagepicker.
- So, when we click on gallery icon before the camera preview starts, we’re stopping the preview before it even started due to which the plugin throws some error and the app crashes
- Slack thread - https://fylein.slack.com/archives/CFGRGRY2X/p1676738064418799
> Stop camera only if it is in RUNNING state

- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
- src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
- src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Fixes two bugs found during testing
- When changing the project to None, the dependent fields are still visible
- When loading form in edit expense, the if there is a child dependent field, but the value selected in parent field does not have any values for the child field, the child field is still shown.
> Dependent Fields: Fix bugs in implementation

- src/app/core/services/accounts.service.ts
BR: https://app.clickup.com/t/85zrpeepz
- The issue here was that for every allowed payment mode, we were using `array.find()` which gave us the first account matching the payment mode. 
- This works for PERONAL/COMPANY/CCC accounts, but a user can have multiple ADVANCE accounts and in that case, only the first advance account will be shown.
This change does not affect the code coverage of the service, so no changes needed in unit tests.
Tested for a few settings of payment modes lgtm 👍
> BR: Filter all accounts for a particular payment mode

- hooks/utils/ios-info.js
Clickup - https://app.clickup.com/t/85zrrnnx9
- This bypasses the confirmation popover asking if our app uses encryption that we see everytime before releasing ios apps.
- With this, the app will be live on testflight once the appflow build process completes without the need to go to the store and add confirmation.
Apple developer ref doc - https://developer.apple.com/documentation/security/complying_with_encryption_export_regulations
Documentation of the added key - https://developer.apple.com/documentation/bundleresources/information_property_list/itsappusesnonexemptencryption
> fix: Update info.plist to avoid encryption confirmation popover when deploying ios app

- src/app/core/services/split-expense.service.ts
- src/app/fyle/split-expense/split-expense.page.ts
Clickup Link - https://app.clickup.com/t/85zrtbkgq
Changes:
- When expense is split by project, remove all dependent fields from custom properties
- If any of the selected project is same as the original expense project, then use the same dependent field values
> fix: Dependent Fields: Remove project dep fields when splitting expense by project

- .github/workflows/live-update.yml
Clickup - https://app.clickup.com/t/85zrummcd
- Have created an environment in mobile app repo which needs approval from Abhishek, Dhar or Me
- Have not tested this action since it has to be merged to master for us to be able to run it.
How this works?
- We trigger the action from github and the live update gets deployed on staging.
- Once the staging live udpate is tested, either of the approver can approve the github action and deploy it to prod
> feat: Add github action to trigger staging live update

- src/app/fyle/my-view-report/my-view-report.page.html
- src/app/fyle/view-team-report/view-team-report.page.html
1. We want to show the date on which the report was submitted, but we actually display the date the report was created on
2. I have swapped `rp_created_at` to `rp_submitted_at`, hence it should now show the correct submission date.
> fix: Report Submission Date Mismatch

- src/app/core/services/report.service.spec.ts
- src/app/core/services/report.service.ts
> fix: remove /txns from create report flow

- src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
- src/app/shared/components/fy-select-project/fy-select-project.component.ts
fix: Linting errors from fy-select-project.component
With this change, all the select project fields are working as expected
Overall `Fixed 29 Linting errors` from the file.
https://github.com/fylein/fyle-mobile-app/assets/104154041/0bd46dbe-8750-464f-91aa-aa33ff0c4ac5
[Please add the link here](https://app.clickup.com/t/86cv8dvba)
> fix: Linting errors from fy-select-project.component

- src/app/core/models/platform/platform-project.model.ts
- src/app/core/models/v2/project-v2.model.ts
- src/app/core/services/projects.service.ts
As per the discussion in thread: https://fylein.slack.com/archives/C06M78V7JKD/p1713850203385719
Optional fields from `ProjectV2`
```diff
export interface ProjectV2 {
-  ap1_email?: string;
-  ap1_full_name?: string;
-  ap2_email?: string;
-  ap2_full_name?: string;
-  project_approver1_id?: string;
-  project_approver2_id?: string;
}
```
```diff
+ Created PlatformProject interface
+ Add transformToV1Response method
+ Add transformToV2Response method
```
[Please add link here](https://app.clickup.com/t/86cv9vhfa)
> feat: Add transformToV1Response & transformToV2Response for PlatformProject

- src/app/core/services/merge-expenses.service.spec.ts
- src/app/core/services/merge-expenses.service.ts
- src/app/core/services/projects.service.spec.ts
- src/app/core/services/recently-used-items.service.spec.ts
- src/app/core/services/recently-used-items.service.ts
- src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
- src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
- src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
- src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
- src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
Before starting with any changes what I have observed is in some places we are using service name as `projectsService` and in some `projectService` and hence while invoking the service functions I need to check in two different places. This PR is just to fix that inconsistency.
[Please add link here](https://app.clickup.com/t/86cv9n9jw)
> fix: Make projectService name consistent

- src/app/core/services/platform/v1/spender/reports.service.spec.ts
- src/app/core/services/platform/v1/spender/reports.service.ts
Context:
- On removal of an expense from a report, the cached data for expenses was causing an issue in displaying correct expense info for a report
- This PR adds back clearing transaction cache to show correct report data after expense removal
> fix: Add cache buster

- src/app/core/mock-data/org-category.data.ts
- src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
- src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
Found one bug while testing...
What is the bug? Fy-select-project-modal is not working properly with newly selected projects, it is working properly with recently used projects.
Solution: I have figured out a solution. The problem is I am making call for allActiveCategories in fy-select-project-modal, instead, I need to get only selected categories. So making fixing changes.
[click-up](https://app.clickup.com/t/86cvjxg6j)
> fix: Fy-select-project-modal is not working properly with new selected

- src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
- src/app/fyle/add-edit-expense/add-edit-expense.page.ts
fixed getCategoryById duplicate calls in add-edit expense page
https://github.com/fylein/fyle-mobile-app/assets/132900359/b9e86479-4f14-4d6c-94c3-581a118f7895
https://github.com/fylein/fyle-mobile-app/assets/132900359/8df3b1b2-08f6-42ad-80aa-e1ca95a690ec
https://app.clickup.com/t/86cvhh5wr
> fix: fixed getCategoryById duplicate calls in add-edit expense page

- src/app/core/mock-data/platform/v1/platform-projects-params.data.ts
- src/app/core/services/projects.service.ts
ClickUp: https://app.clickup.com/t/86cvy3jnh
The sub project field was not being included while searching projects, added both `name` and `sub_project` to `or` param here.
> fix: include sub project in projects search

- src/app/core/services/projects.service.ts
ProjectsService.getByParamsUnformatted query param bug
This did not give any error because we are always passing sortOrder = "name" by default.
[clickup link](https://app.clickup.com/t/86cvz4km4)
> fix: ProjectsService.getByParamsUnformatted query param bug

- src/app/fyle/team-reports/team-reports.page.ts
TypeError
s.complete is not a function. (In 's.complete()', 's.complete' is undefined)
The error `s.complete() is not a function` occurs when the `complete` method is either undefined or not a function on the target object. I confirmed through console logs that `event.target` is a valid `ion-infinite-scroll` element, and the `complete` method exists as a function. However, if the method doesn't exist for a specific user, it might be missing or incorrectly bound to the target element. As a fallback, I implemented a check to ensure that if `event.target` or `complete` isn't a function, the `complete` method won't be called, preventing the error.
> fix: complete method typeerror

- src/app/fyle/my-expenses/my-expenses.page.ts
- src/app/fyle/team-reports/team-reports.page.ts
TypeError
i.complete is not a function. (In 'i.complete()', 'i.complete' is undefined)
Solved using optional chaining on the complete method too
The error i.complete() is not a function occurs when the complete method is either undefined or not a function on the target object. I confirmed through console logs that event.target is a valid ion-infinite-scroll element, and the complete method exists as a function. However, if the method doesn't exist for a specific user, it might be missing or incorrectly bound to the target element. As a fallback, I implemented a check using the optional chaining to ensure that if event.target or complete isn't a function, the complete method won't be called, preventing the error.
> fix: my expenses complete method typeerror

- src/app/core/mock-data/extended-org-user.data.ts
- src/app/core/mock-data/platform/v1/delegator.data.ts
- src/app/core/mock-data/platform/v1/platform-employee.data.ts
- src/app/core/models/employee-params.model.ts
- src/app/core/models/platform/delegatee.model.ts
- src/app/core/models/platform/delegation-type.enum.ts
- src/app/core/models/platform/delegator.model.ts
- src/app/core/models/platform/platform-employee.model.ts
- src/app/core/services/org-user.service.spec.ts
- src/app/core/services/org-user.service.ts
- src/app/core/services/platform/v1/spender/employees.service.spec.ts
- src/app/core/services/platform/v1/spender/employees.service.ts
- src/app/fyle/delegated-accounts/delegated-accounts.page.html
- src/app/fyle/delegated-accounts/delegated-accounts.page.spec.ts
- src/app/fyle/delegated-accounts/delegated-accounts.page.ts
- src/app/fyle/notifications/notifications.page.spec.ts
- src/app/fyle/notifications/notifications.page.ts
- src/app/shared/components/sidemenu/sidemenu.component.spec.ts
- src/app/shared/components/sidemenu/sidemenu.component.ts
> fix: Replace public implementation to display delegatee info with platform 

- src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.spec.ts
- src/app/fyle/potential-duplicates/potential-duplicates.page.spec.ts
https://app.clickup.com/t/86cw6epbu
> test: Added unit test cases for dismiss dialog

- src/app/core/interceptors/httpInterceptor.spec.ts
- src/app/core/interceptors/httpInterceptor.ts
- src/app/fyle/personal-cards/personal-cards.page.ts
Fixing the behavioural bug in httpInterceptor which occurred when we have multiple requests and the token is about to expire then triggering refreshToken some of the requests were getting old or null as token
Fixed by changing the intercept method and also using switchMap instead of concatMap
> fix: httpInterceptor behavioural bug

- .github/workflows/appflow-master.yml
- .github/workflows/appflow-release-branch.yml
- .github/workflows/manual-appflow-1.yml
- .github/workflows/manual-appflow-with-inputs.yml
> fix: Update artifact version

- src/app/fyle/my-expenses/my-expenses.page.spec.ts
- src/app/fyle/my-expenses/my-expenses.page.ts
https://app.clickup.com/t/86cwgw4wr
> test: Add unit tests for DE polling
